//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;+&quot; expected.
        /// </summary>
        public static string AddExpected {
            get {
                return ResourceManager.GetString("AddExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&amp;&amp;&quot; expected.
        /// </summary>
        public static string AndAndExpected {
            get {
                return ResourceManager.GetString("AndAndExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&amp;&quot; expected.
        /// </summary>
        public static string AndExpected {
            get {
                return ResourceManager.GetString("AndExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;*&quot; expected.
        /// </summary>
        public static string AsteriskExpected {
            get {
                return ResourceManager.GetString("AsteriskExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute argument must be a constant expression.
        /// </summary>
        public static string AttributeArgMustBeConstant {
            get {
                return ResourceManager.GetString("AttributeArgMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;base&apos; is expected here to call base constructor.
        /// </summary>
        public static string BaseIsExpectedToCallBaseConstructor {
            get {
                return ResourceManager.GetString("BaseIsExpectedToCallBaseConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;catch&quot; expected.
        /// </summary>
        public static string CatchExpected {
            get {
                return ResourceManager.GetString("CatchExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char expected.
        /// </summary>
        public static string char_expected {
            get {
                return ResourceManager.GetString("char_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if all the elements in the specified list are of the same type.
        /// </summary>
        public static string CheckIfTheElementsInListAreSameType {
            get {
                return ResourceManager.GetString("CheckIfTheElementsInListAreSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if each of rows in multidimensional list has the same number of elements .
        /// </summary>
        public static string ChecksIfLengthsAreSameInMultiDimentionalList {
            get {
                return ResourceManager.GetString("ChecksIfLengthsAreSameInMultiDimentionalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if the specified element is present in the specified list.
        /// </summary>
        public static string ChecksIfListContainsTheElement {
            get {
                return ResourceManager.GetString("ChecksIfListContainsTheElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if all elements in the specified list are false.
        /// </summary>
        public static string ChecksIfTheListIsAllFalse {
            get {
                return ResourceManager.GetString("ChecksIfTheListIsAllFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if all elements in the specified list are true.
        /// </summary>
        public static string ChecksIfTheListIsAllTrue {
            get {
                return ResourceManager.GetString("ChecksIfTheListIsAllTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if the list has a uniform depth.
        /// </summary>
        public static string ChecksListWithUniformDepth {
            get {
                return ResourceManager.GetString("ChecksListWithUniformDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closebracket expected.
        /// </summary>
        public static string closebracket_expected {
            get {
                return ResourceManager.GetString("closebracket_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; expected - Imcomplete Closure.
        /// </summary>
        public static string CloseBracketExpected {
            get {
                return ResourceManager.GetString("CloseBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;}&quot; expected.
        /// </summary>
        public static string CloseCurlyBracketExpected {
            get {
                return ResourceManager.GetString("CloseCurlyBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closeparen expected.
        /// </summary>
        public static string closeparen_expected {
            get {
                return ResourceManager.GetString("closeparen_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;,&quot; expected.
        /// </summary>
        public static string CommaExpected {
            get {
                return ResourceManager.GetString("CommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if the specified key is present in the specified key-value pair list.
        /// </summary>
        public static string ContainsKeys {
            get {
                return ResourceManager.GetString("ContainsKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;~&quot; expected.
        /// </summary>
        public static string CurverDashExpected {
            get {
                return ResourceManager.GetString("CurverDashExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;--&quot; expected.
        /// </summary>
        public static string DashExpected {
            get {
                return ResourceManager.GetString("DashExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether two object instances are equal.
        /// </summary>
        public static string DeterminesObjectsAreEqual {
            get {
                return ResourceManager.GetString("DeterminesObjectsAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;:&quot; expected.
        /// </summary>
        public static string DoubleColumnExpected {
            get {
                return ResourceManager.GetString("DoubleColumnExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;||&quot; expected.
        /// </summary>
        public static string DoubleDashExpected {
            get {
                return ResourceManager.GetString("DoubleDashExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty character literal.
        /// </summary>
        public static string EmptyCharacterLiteral {
            get {
                return ResourceManager.GetString("EmptyCharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endline_expected.
        /// </summary>
        public static string endline_expected {
            get {
                return ResourceManager.GetString("endline_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOF expected.
        /// </summary>
        public static string EOF_expected {
            get {
                return ResourceManager.GetString("EOF_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equal expected.
        /// </summary>
        public static string equal_expected {
            get {
                return ResourceManager.GetString("equal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;=&quot; expected.
        /// </summary>
        public static string EqualExpected {
            get {
                return ResourceManager.GetString("EqualExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;=&gt;&quot; expected.
        /// </summary>
        public static string EqualRightExpected {
            get {
                return ResourceManager.GetString("EqualRightExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import {0}.
        /// </summary>
        public static string FailedToImport {
            get {
                return ResourceManager.GetString("FailedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float expected.
        /// </summary>
        public static string float_expected {
            get {
                return ResourceManager.GetString("float_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function called {0} could be found. Please check the name of the function.
        /// </summary>
        public static string FUNCTION_GROUP_RESOLUTION_FAILURE {
            get {
                return ResourceManager.GetString("FUNCTION_GROUP_RESOLUTION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function call is not allowed to the left hand side of an assignment.
        /// </summary>
        public static string FunctionCallCannotBeAtLeftSide {
            get {
                return ResourceManager.GetString("FunctionCallCannotBeAtLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets all keys from the specified key-value pair list.
        /// </summary>
        public static string GetKeys {
            get {
                return ResourceManager.GetString("GetKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the Type of the current instance.
        /// </summary>
        public static string Gettypes {
            get {
                return ResourceManager.GetString("Gettypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets all values stored in the specified key-value pair list and for a simple list it returns all elements in the list.
        /// </summary>
        public static string GetValues {
            get {
                return ResourceManager.GetString("GetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greaterequal expected.
        /// </summary>
        public static string greaterequal_expected {
            get {
                return ResourceManager.GetString("greaterequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greaterthan expected.
        /// </summary>
        public static string greaterthan_expected {
            get {
                return ResourceManager.GetString("greaterthan_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;#&quot; expected.
        /// </summary>
        public static string HexExpected {
            get {
                return ResourceManager.GetString("HexExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ident expected.
        /// </summary>
        public static string ident_expected {
            get {
                return ResourceManager.GetString("ident_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports data from a text file containing comma separated values into two-dimensional list.
        /// </summary>
        public static string ImportFileByGivenFilePath {
            get {
                return ResourceManager.GetString("ImportFileByGivenFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports data from a text file containing comma separated values into two-dimensional list and also transpose the output list if specified.
        /// </summary>
        public static string ImportFileByGivenFilePathWithMode {
            get {
                return ResourceManager.GetString("ImportFileByGivenFilePathWithMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports statements are not supported in CodeBlock Nodes.
        /// </summary>
        public static string ImportStatementNotSupported {
            get {
                return ResourceManager.GetString("ImportStatementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;in&quot; expected.
        /// </summary>
        public static string InExpected {
            get {
                return ResourceManager.GetString("InExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts an element into a list at specified index.
        /// </summary>
        public static string InsertsAnElementIntoList {
            get {
                return ResourceManager.GetString("InsertsAnElementIntoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_functiondecl.
        /// </summary>
        public static string InvalidAssociativeAccessFunctiondecl {
            get {
                return ResourceManager.GetString("InvalidAssociativeAccessFunctiondecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_AccessSpecifier.
        /// </summary>
        public static string InvalidAssociativeAccessSpecifier {
            get {
                return ResourceManager.GetString("InvalidAssociativeAccessSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_AddOp.
        /// </summary>
        public static string InvalidAssociativeAddOp {
            get {
                return ResourceManager.GetString("InvalidAssociativeAddOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_BinaryOps.
        /// </summary>
        public static string InvalidAssociativeBinaryOps {
            get {
                return ResourceManager.GetString("InvalidAssociativeBinaryOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_BitOp.
        /// </summary>
        public static string InvalidAssociativeBitOp {
            get {
                return ResourceManager.GetString("InvalidAssociativeBitOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_classdecl.
        /// </summary>
        public static string InvalidAssociativeClassdecl {
            get {
                return ResourceManager.GetString("InvalidAssociativeClassdecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_ComparisonOp.
        /// </summary>
        public static string InvalidAssociativeComparisonOp {
            get {
                return ResourceManager.GetString("InvalidAssociativeComparisonOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_DecoratedIdentifier.
        /// </summary>
        public static string InvalidAssociativeDecoratedIdentifier {
            get {
                return ResourceManager.GetString("InvalidAssociativeDecoratedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_Factor.
        /// </summary>
        public static string InvalidAssociativeFactor {
            get {
                return ResourceManager.GetString("InvalidAssociativeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_functiondecl.
        /// </summary>
        public static string InvalidAssociativeFunctionaldecl {
            get {
                return ResourceManager.GetString("InvalidAssociativeFunctionaldecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_FunctionalStatement.
        /// </summary>
        public static string InvalidAssociativeFunctionalStatement {
            get {
                return ResourceManager.GetString("InvalidAssociativeFunctionalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_LanguageBlock.
        /// </summary>
        public static string InvalidAssociativeLanguageBlock {
            get {
                return ResourceManager.GetString("InvalidAssociativeLanguageBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_LogicalOp.
        /// </summary>
        public static string InvalidAssociativeLogicalOp {
            get {
                return ResourceManager.GetString("InvalidAssociativeLogicalOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_MulOp.
        /// </summary>
        public static string InvalidAssociativeMulOp {
            get {
                return ResourceManager.GetString("InvalidAssociativeMulOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_NameReference.
        /// </summary>
        public static string InvalidAssociativeNameReference {
            get {
                return ResourceManager.GetString("InvalidAssociativeNameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_negop.
        /// </summary>
        public static string InvalidAssociativeNegop {
            get {
                return ResourceManager.GetString("InvalidAssociativeNegop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_Number.
        /// </summary>
        public static string InvalidAssociativeNumber {
            get {
                return ResourceManager.GetString("InvalidAssociativeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_PostFixOp.
        /// </summary>
        public static string InvalidAssociativePostFixOp {
            get {
                return ResourceManager.GetString("InvalidAssociativePostFixOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_Statement.
        /// </summary>
        public static string InvalidAssociativeStatement {
            get {
                return ResourceManager.GetString("InvalidAssociativeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_UnaryExpression.
        /// </summary>
        public static string InvalidAssociativeUnaryExpression {
            get {
                return ResourceManager.GetString("InvalidAssociativeUnaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Associative_unaryop.
        /// </summary>
        public static string InvalidAssociativeUnaryop {
            get {
                return ResourceManager.GetString("InvalidAssociativeUnaryop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Hydrogen.
        /// </summary>
        public static string InvalidHydrogen {
            get {
                return ResourceManager.GetString("InvalidHydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_addop.
        /// </summary>
        public static string InvalidImperativeAddop {
            get {
                return ResourceManager.GetString("InvalidImperativeAddop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_assignstmt.
        /// </summary>
        public static string InvalidImperativeAssignstmt {
            get {
                return ResourceManager.GetString("InvalidImperativeAssignstmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_bitop.
        /// </summary>
        public static string InvalidImperativeBitop {
            get {
                return ResourceManager.GetString("InvalidImperativeBitop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_decoratedIdentifier.
        /// </summary>
        public static string InvalidImperativeDecoratedIdentifier {
            get {
                return ResourceManager.GetString("InvalidImperativeDecoratedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_factor.
        /// </summary>
        public static string InvalidImperativeFactor {
            get {
                return ResourceManager.GetString("InvalidImperativeFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_forloop.
        /// </summary>
        public static string InvalidImperativeForLoop {
            get {
                return ResourceManager.GetString("InvalidImperativeForLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_ifstmt.
        /// </summary>
        public static string InvalidImperativeIfstmt {
            get {
                return ResourceManager.GetString("InvalidImperativeIfstmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_languageblock.
        /// </summary>
        public static string InvalidImperativeLanguageblock {
            get {
                return ResourceManager.GetString("InvalidImperativeLanguageblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_logicalop.
        /// </summary>
        public static string InvalidImperativeLogicallop {
            get {
                return ResourceManager.GetString("InvalidImperativeLogicallop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_mulop.
        /// </summary>
        public static string InvalidImperativeMulop {
            get {
                return ResourceManager.GetString("InvalidImperativeMulop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_NameReference.
        /// </summary>
        public static string InvalidImperativeNameReference {
            get {
                return ResourceManager.GetString("InvalidImperativeNameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_num.
        /// </summary>
        public static string InvalidImperativeNum {
            get {
                return ResourceManager.GetString("InvalidImperativeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_PostFixOp.
        /// </summary>
        public static string InvalidImperativePostFixOp {
            get {
                return ResourceManager.GetString("InvalidImperativePostFixOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_relop.
        /// </summary>
        public static string InvalidImperativeRelop {
            get {
                return ResourceManager.GetString("InvalidImperativeRelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_stmt.
        /// </summary>
        public static string InvalidImperativeStmt {
            get {
                return ResourceManager.GetString("InvalidImperativeStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_unaryexpr.
        /// </summary>
        public static string InvalidImperativeUnaryexpr {
            get {
                return ResourceManager.GetString("InvalidImperativeUnaryexpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Imperative_unaryop.
        /// </summary>
        public static string InvalidImperativeUnaryop {
            get {
                return ResourceManager.GetString("InvalidImperativeUnaryop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Import_Statement.
        /// </summary>
        public static string InvalidImportStatement {
            get {
                return ResourceManager.GetString("InvalidImportStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot; is not a valid language block identifier, do you mean \&quot;Associative\&quot; or \&quot;Imperative\&quot;?.
        /// </summary>
        public static string InvalidLanguageBlockIdentifier {
            get {
                return ResourceManager.GetString("InvalidLanguageBlockIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return statement is invalid. Do you mean: return = {0} ?.
        /// </summary>
        public static string InvalidReturnStatement {
            get {
                return ResourceManager.GetString("InvalidReturnStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error: invalid symbol &apos;{0}&apos;. (Did you mean to use Modifier Stack \&quot; =&gt; \&quot;).
        /// </summary>
        public static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File : &apos;{0}&apos; is already imported.
        /// </summary>
        public static string kAlreadyImported {
            get {
                return ResourceManager.GetString("kAlreadyImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate function could not be located on final replicated dispatch GUARD {FDD1F347-A9A6-43FB-A08E-A5E793EC3920}.
        /// </summary>
        public static string kAmbigousMethodDispatch {
            get {
                return ResourceManager.GetString("kAmbigousMethodDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; of argument &apos;{1}&apos; is not defined.
        /// </summary>
        public static string kArgumentTypeUndefined {
            get {
                return ResourceManager.GetString("kArgumentTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable is over indexed.
        /// </summary>
        public static string kArrayOverIndexed {
            get {
                return ResourceManager.GetString("kArrayOverIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type conversion would cause array rank reduction. This is not permitted outside of replication. {511ED65F-FB66-4709-BDDA-DCD5E053B87F}.
        /// </summary>
        public static string kArrayRankReduction {
            get {
                return ResourceManager.GetString("kArrayRankReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only character can be assigned to a position in a string.
        /// </summary>
        public static string kAssignNonCharacterToString {
            get {
                return ResourceManager.GetString("kAssignNonCharacterToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;this&apos; is readonly and cannot be assigned to.
        /// </summary>
        public static string kAssingToThis {
            get {
                return ResourceManager.GetString("kAssingToThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call constructor &apos;{0}()&apos; in itself.
        /// </summary>
        public static string kCallingConstructorInConstructor {
            get {
                return ResourceManager.GetString("kCallingConstructorInConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call constructor &apos;{0}()&apos; on instance.
        /// </summary>
        public static string KCallingConstructorOnInstance {
            get {
                return ResourceManager.GetString("KCallingConstructorOnInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}()&apos; is not a static method.
        /// </summary>
        public static string kCallingNonStaticMethod {
            get {
                return ResourceManager.GetString("kCallingNonStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; is not a static property.
        /// </summary>
        public static string kCallingNonStaticProperty {
            get {
                return ResourceManager.GetString("kCallingNonStaticProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Runtime warning: {0}\n - \&quot;{1}\&quot; &lt;line: {2}, col: {3}&gt;.
        /// </summary>
        public static string kConsoleWarningMessage {
            get {
                return ResourceManager.GetString("kConsoleWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting an array to {0} would cause array rank reduction and is not permitted.
        /// </summary>
        public static string kConvertArrayToNonArray {
            get {
                return ResourceManager.GetString("kConvertArrayToNonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting double to int will cause possible information loss.
        /// </summary>
        public static string kConvertDoubleToInt {
            get {
                return ResourceManager.GetString("kConvertDoubleToInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asked to convert non-convertible types.
        /// </summary>
        public static string kConvertNonConvertibleTypes {
            get {
                return ResourceManager.GetString("kConvertNonConvertibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency detected at &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        public static string kCyclicDependency {
            get {
                return ResourceManager.GetString("kCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dereferencing a non-pointer.
        /// </summary>
        public static string kDeferencingNonPointer {
            get {
                return ResourceManager.GetString("kDeferencingNonPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type &apos;{0}&apos; is not defined.
        /// </summary>
        public static string kExceptionTypeUndefined {
            get {
                return ResourceManager.GetString("kExceptionTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot; is a keyword, can&apos;t be used as constructor name.
        /// </summary>
        public static string keywordCannotBeUsedAsConstructorName {
            get {
                return ResourceManager.GetString("keywordCannotBeUsedAsConstructorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot; is a keyword, identifier expected.
        /// </summary>
        public static string keywordCantBeUsedAsIdentifier {
            get {
                return ResourceManager.GetString("keywordCantBeUsedAsIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting other objects to a function pointer is not allowed.
        /// </summary>
        public static string kFailToConverToFunction {
            get {
                return ResourceManager.GetString("kFailToConverToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting other things to null is not allowed.
        /// </summary>
        public static string kFailToConverToNull {
            get {
                return ResourceManager.GetString("kFailToConverToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting other things to pointer is not allowed.
        /// </summary>
        public static string kFailToConverToPointer {
            get {
                return ResourceManager.GetString("kFailToConverToPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain object &apos;{0}&apos; for &apos;{1}.{2}&apos;.
        /// </summary>
        public static string kFFIFailedToObtainObject {
            get {
                return ResourceManager.GetString("kFFIFailedToObtainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain this object for &apos;{0}.{1}&apos;.
        /// </summary>
        public static string kFFIFailedToObtainThisObject {
            get {
                return ResourceManager.GetString("kFFIFailedToObtainThisObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is being cast to &apos;{1}&apos;, but the allowed range is [{2}..{3}].
        /// </summary>
        public static string kFFIInvalidCast {
            get {
                return ResourceManager.GetString("kFFIInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File : &apos;{0}&apos; not found.
        /// </summary>
        public static string kFileNotFound {
            get {
                return ResourceManager.GetString("kFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No candidate function could be found.
        /// </summary>
        public static string kFunctionNotFound {
            get {
                return ResourceManager.GetString("kFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}()&apos; doesn&apos;t return at all code paths.
        /// </summary>
        public static string kFunctionNotReturnAtAllCodePaths {
            get {
                return ResourceManager.GetString("kFunctionNotReturnAtAllCodePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range.
        /// </summary>
        public static string kIndexOutOfRange {
            get {
                return ResourceManager.GetString("kIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount in range expression should be an positive integer.
        /// </summary>
        public static string kInvalidAmountInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidAmountInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is invalid.
        /// </summary>
        public static string kInvalidArguments {
            get {
                return ResourceManager.GetString("kInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value that used in range expression should be either integer or double.
        /// </summary>
        public static string kInvalidArgumentsInRangeExpression {
            get {
                return ResourceManager.GetString("kInvalidArgumentsInRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement break causes function to abnormally return null.
        /// </summary>
        public static string kInvalidBreakForFunction {
            get {
                return ResourceManager.GetString("kInvalidBreakForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement continue cause function to abnormally return null.
        /// </summary>
        public static string kInvalidContinueForFunction {
            get {
                return ResourceManager.GetString("kInvalidContinueForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency detected at &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        public static string kInvalidStaticCyclicDependency {
            get {
                return ResourceManager.GetString("kInvalidStaticCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;this&apos; can only be used in member methods.
        /// </summary>
        public static string kInvalidThis {
            get {
                return ResourceManager.GetString("kInvalidThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}()&apos; is invoked on invalid object.
        /// </summary>
        public static string kInvokeMethodOnInvalidObject {
            get {
                return ResourceManager.GetString("kInvokeMethodOnInvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}()&apos; is already defined.
        /// </summary>
        public static string kMethodAlreadyDefined {
            get {
                return ResourceManager.GetString("kMethodAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}()&apos; has some invalid arguments.
        /// </summary>
        public static string kMethodHasInvalidArguments {
            get {
                return ResourceManager.GetString("kMethodHasInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}()&apos; is inaccessible.
        /// </summary>
        public static string kMethodIsInaccessible {
            get {
                return ResourceManager.GetString("kMethodIsInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}()&apos; not found.
        /// </summary>
        public static string kMethodNotFound {
            get {
                return ResourceManager.GetString("kMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method resolution failure on: {0}() - 0CD069F4-6C8A-42B6-86B1-B5C17072751B.
        /// </summary>
        public static string kMethodResolutionFailure {
            get {
                return ResourceManager.GetString("kMethodResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; cannot be applied to operands of type &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        public static string kMethodResolutionFailureForOperator {
            get {
                return ResourceManager.GetString("kMethodResolutionFailureForOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the input types are not matching, please check that the right variable types are being passed to the inputs. Couldn&apos;t find a version of {0} that takes arguments of type {1}.
        /// </summary>
        public static string kMethodResolutionFailureWithTypes {
            get {
                return ResourceManager.GetString("kMethodResolutionFailureWithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack overflow caused by calling method &apos;{0}()&apos; recursively..
        /// </summary>
        public static string kMethodStackOverflow {
            get {
                return ResourceManager.GetString("kMethodStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple definitions for &apos;{0}&apos; are found as {1}.
        /// </summary>
        public static string kMultipleSymbolFound {
            get {
                return ResourceManager.GetString("kMultipleSymbolFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple definitions for &apos;{0}&apos; are found as {1}.
        /// </summary>
        public static string kMultipleSymbolFoundFromName {
            get {
                return ResourceManager.GetString("kMultipleSymbolFoundFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No step size is specified in amount range expression.
        /// </summary>
        public static string kNoStepSizeInAmountRangeExpression {
            get {
                return ResourceManager.GetString("kNoStepSizeInAmountRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is inaccessible.
        /// </summary>
        public static string kPropertyInaccessible {
            get {
                return ResourceManager.GetString("kPropertyInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is inaccessible.
        /// </summary>
        public static string kPropertyIsInaccessible {
            get {
                return ResourceManager.GetString("kPropertyIsInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found.
        /// </summary>
        public static string kPropertyNotFound {
            get {
                return ResourceManager.GetString("kPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; does not have a property &apos;{1}&apos;.
        /// </summary>
        public static string kPropertyOfClassNotFound {
            get {
                return ResourceManager.GetString("kPropertyOfClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount operator cannot be used together with step operator.
        /// </summary>
        public static string kRangeExpressionConflictOperator {
            get {
                return ResourceManager.GetString("kRangeExpressionConflictOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of step is invalid..
        /// </summary>
        public static string kRangeExpressionWithInvalidAmount {
            get {
                return ResourceManager.GetString("kRangeExpressionWithInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step size of range expression is invalid..
        /// </summary>
        public static string kRangeExpressionWithInvalidStepSize {
            get {
                return ResourceManager.GetString("kRangeExpressionWithInvalidStepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step number of range expression should be greater than 0.
        /// </summary>
        public static string kRangeExpressionWithNegativeStepNumber {
            get {
                return ResourceManager.GetString("kRangeExpressionWithNegativeStepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step number of range expression should be integer.
        /// </summary>
        public static string kRangeExpressionWithNonIntegerStepNumber {
            get {
                return ResourceManager.GetString("kRangeExpressionWithNonIntegerStepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step size of range expression should not be 0.
        /// </summary>
        public static string kRangeExpressionWithStepSizeZero {
            get {
                return ResourceManager.GetString("kRangeExpressionWithStepSizeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return type &apos;{0}&apos; of method &apos;{1}()&apos; is not defined.
        /// </summary>
        public static string kReturnTypeUndefined {
            get {
                return ResourceManager.GetString("kReturnTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find static method or constructor {0}.{1}().
        /// </summary>
        public static string kStaticMethodNotFound {
            get {
                return ResourceManager.GetString("kStaticMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String indexing cannot be assigned to, it is read only.
        /// </summary>
        public static string kStringIndexingCannotBeAssigned {
            get {
                return ResourceManager.GetString("kStringIndexingCannotBeAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index to string is out of range.
        /// </summary>
        public static string kStringIndexOutOfRange {
            get {
                return ResourceManager.GetString("kStringIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is over indexed.
        /// </summary>
        public static string kStringOverIndexed {
            get {
                return ResourceManager.GetString("kStringOverIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is over indexed.
        /// </summary>
        public static string kSymbolOverIndexed {
            get {
                return ResourceManager.GetString("kSymbolOverIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not defined.
        /// </summary>
        public static string kTypeUndefined {
            get {
                return ResourceManager.GetString("kTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; hasn&apos;t been defined yet.
        /// </summary>
        public static string kUnboundIdentifierMsg {
            get {
                return ResourceManager.GetString("kUnboundIdentifierMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a static property, so cannot be assigned to static properties or used in static methods..
        /// </summary>
        public static string kUsingNonStaticMemberInStaticContext {
            get {
                return ResourceManager.GetString("kUsingNonStaticMemberInStaticContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;this&apos; cannot be used in static method.
        /// </summary>
        public static string kUsingThisInStaticFunction {
            get {
                return ResourceManager.GetString("kUsingThisInStaticFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_break expected.
        /// </summary>
        public static string kw_break_expected {
            get {
                return ResourceManager.GetString("kw_break_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_class expected.
        /// </summary>
        public static string kw_class_expected {
            get {
                return ResourceManager.GetString("kw_class_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_constructor expected.
        /// </summary>
        public static string kw_constructor_expected {
            get {
                return ResourceManager.GetString("kw_constructor_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_continue expected.
        /// </summary>
        public static string Kw_continue_expected {
            get {
                return ResourceManager.GetString("Kw_continue_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_def expected.
        /// </summary>
        public static string kw_def_expected {
            get {
                return ResourceManager.GetString("kw_def_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_else expected.
        /// </summary>
        public static string kw_else_expected {
            get {
                return ResourceManager.GetString("kw_else_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_elseif expected.
        /// </summary>
        public static string kw_elseif_expected {
            get {
                return ResourceManager.GetString("kw_elseif_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_extend expected.
        /// </summary>
        public static string kw_extend_expected {
            get {
                return ResourceManager.GetString("kw_extend_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_external expected.
        /// </summary>
        public static string kw_external_expected {
            get {
                return ResourceManager.GetString("kw_external_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_for expected.
        /// </summary>
        public static string kw_for_expected {
            get {
                return ResourceManager.GetString("kw_for_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_from expected.
        /// </summary>
        public static string kw_from_expected {
            get {
                return ResourceManager.GetString("kw_from_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_heap expected.
        /// </summary>
        public static string kw_heap_expected {
            get {
                return ResourceManager.GetString("kw_heap_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_if expected.
        /// </summary>
        public static string kw_if_expected {
            get {
                return ResourceManager.GetString("kw_if_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_import expected.
        /// </summary>
        public static string kw_import_expected {
            get {
                return ResourceManager.GetString("kw_import_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_local expected.
        /// </summary>
        public static string Kw_Local_expected {
            get {
                return ResourceManager.GetString("Kw_Local_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_native expected.
        /// </summary>
        public static string kw_native_expected {
            get {
                return ResourceManager.GetString("kw_native_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_prefix expected.
        /// </summary>
        public static string kw_prefix_expected {
            get {
                return ResourceManager.GetString("kw_prefix_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_static expected.
        /// </summary>
        public static string Kw_static_expected {
            get {
                return ResourceManager.GetString("Kw_static_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw_while expected.
        /// </summary>
        public static string kw_while_expected {
            get {
                return ResourceManager.GetString("kw_while_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lessequal expected.
        /// </summary>
        public static string lessequal_expected {
            get {
                return ResourceManager.GetString("lessequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lessthan expected.
        /// </summary>
        public static string lessthan_expected {
            get {
                return ResourceManager.GetString("lessthan_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal_false expected.
        /// </summary>
        public static string Literal_false_expected {
            get {
                return ResourceManager.GetString("Literal_false_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal_null expected.
        /// </summary>
        public static string Literal_null_expected {
            get {
                return ResourceManager.GetString("Literal_null_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal_true expected.
        /// </summary>
        public static string Literal_true_expected {
            get {
                return ResourceManager.GetString("Literal_true_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps a vlaue from one range to another range.
        /// </summary>
        public static string MapsValueFromOneRangeToAnotherRange {
            get {
                return ResourceManager.GetString("MapsValueFromOneRangeToAnotherRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps a value into an input range.
        /// </summary>
        public static string MapsValueIntoInputRange {
            get {
                return ResourceManager.GetString("MapsValueIntoInputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Blocks are not supported currently.
        /// </summary>
        public static string ModifierBlockNotSupported {
            get {
                return ResourceManager.GetString("ModifierBlockNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer modulo by zero.
        /// </summary>
        public static string ModuloByZero {
            get {
                return ResourceManager.GetString("ModuloByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neg expected.
        /// </summary>
        public static string neg_expected {
            get {
                return ResourceManager.GetString("neg_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructors for Attribute &apos;{0}&apos; takes {1} arguments.
        /// </summary>
        public static string NoConstructorForAttribute {
            get {
                return ResourceManager.GetString("NoConstructorForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import file: &apos;{0}&apos;: No such file or directory.
        /// </summary>
        public static string NoSuchFileOrDirectoryToImport {
            get {
                return ResourceManager.GetString("NoSuchFileOrDirectoryToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not expected.
        /// </summary>
        public static string not_expected {
            get {
                return ResourceManager.GetString("not_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notequal expected.
        /// </summary>
        public static string notequal_expected {
            get {
                return ResourceManager.GetString("notequal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number expected.
        /// </summary>
        public static string number_expected {
            get {
                return ResourceManager.GetString("number_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns objects that are included in List1 but excluded in List2.
        /// </summary>
        public static string ObjectsContainsInList1NotInList2 {
            get {
                return ResourceManager.GetString("ObjectsContainsInList1NotInList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openbracket expected.
        /// </summary>
        public static string openbracket_expected {
            get {
                return ResourceManager.GetString("openbracket_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{&quot; expected.
        /// </summary>
        public static string OpenCurlyBracketExpected {
            get {
                return ResourceManager.GetString("OpenCurlyBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openparen expected.
        /// </summary>
        public static string openparen_expected {
            get {
                return ResourceManager.GetString("openparen_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period expected.
        /// </summary>
        public static string period_expected {
            get {
                return ResourceManager.GetString("period_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipe expected.
        /// </summary>
        public static string pipe_expected {
            get {
                return ResourceManager.GetString("pipe_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;++&quot; expected.
        /// </summary>
        public static string PlusExpected {
            get {
                return ResourceManager.GetString("PlusExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postfixed_replicationguide expected.
        /// </summary>
        public static string postfixed_replicationguide_expected {
            get {
                return ResourceManager.GetString("postfixed_replicationguide_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;^&quot; expected.
        /// </summary>
        public static string PowerExpected {
            get {
                return ResourceManager.GetString("PowerExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;private&quot; expected.
        /// </summary>
        public static string PrivatedExpected {
            get {
                return ResourceManager.GetString("PrivatedExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produces the set intersection of two sequences.
        /// </summary>
        public static string ProducesTheSetIntersection {
            get {
                return ResourceManager.GetString("ProducesTheSetIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produces the set union of two sequences by using the default equality comparer.
        /// </summary>
        public static string ProducesTheSetUnion {
            get {
                return ResourceManager.GetString("ProducesTheSetUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;protected&quot; expected.
        /// </summary>
        public static string ProtectedExpected {
            get {
                return ResourceManager.GetString("ProtectedExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;public&quot; expected.
        /// </summary>
        public static string PublicExpected {
            get {
                return ResourceManager.GetString("PublicExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? expected.
        /// </summary>
        public static string QuestionExpected {
            get {
                return ResourceManager.GetString("QuestionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;?&quot; expected.
        /// </summary>
        public static string QuestionMarkExpected {
            get {
                return ResourceManager.GetString("QuestionMarkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rangeop_expected.
        /// </summary>
        public static string rangeop_expected {
            get {
                return ResourceManager.GetString("rangeop_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &quot;%&quot; expected.
        /// </summary>
        public static string RemainderExpected {
            get {
                return ResourceManager.GetString("RemainderExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns true if the specified key is removed from list, otherwise returns false.
        /// </summary>
        public static string RemoveKeys {
            get {
                return ResourceManager.GetString("RemoveKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the members of the list which are not members of the specified type.
        /// </summary>
        public static string RemovesTheMembersofTheList {
            get {
                return ResourceManager.GetString("RemovesTheMembersofTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorders the list using the specified indices.
        /// </summary>
        public static string ReordersList {
            get {
                return ResourceManager.GetString("ReordersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replicationguide_postfix expected.
        /// </summary>
        public static string Replicationguide_postfix_expected {
            get {
                return ResourceManager.GetString("Replicationguide_postfix_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joins two lists into a single list.
        /// </summary>
        public static string ReturnsConcatenatingList {
            get {
                return ResourceManager.GetString("ReturnsConcatenatingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns multidimentional list according the rank given.
        /// </summary>
        public static string ReturnsListWithRankDepth {
            get {
                return ResourceManager.GetString("ReturnsListWithRankDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a list with uniform depth as specified by the input depth.
        /// </summary>
        public static string ReturnsListWithUniformDepth {
            get {
                return ResourceManager.GetString("ReturnsListWithUniformDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns number of items in the specified list.
        /// </summary>
        public static string ReturnsNumberOfItems {
            get {
                return ResourceManager.GetString("ReturnsNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statement is not allowed in constructor.
        /// </summary>
        public static string ReturnStatementIsNotAllowedInConstructor {
            get {
                return ResourceManager.GetString("ReturnStatementIsNotAllowedInConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the deepest depth of the list.
        /// </summary>
        public static string ReturnsTheDeepestDepthOfTheList {
            get {
                return ResourceManager.GetString("ReturnsTheDeepestDepthOfTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the flattened 1D list of the multi-dimensional input list.
        /// </summary>
        public static string ReturnsTheFlattened1DList {
            get {
                return ResourceManager.GetString("ReturnsTheFlattened1DList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the index of the member in the list.
        /// </summary>
        public static string ReturnsTheIndex {
            get {
                return ResourceManager.GetString("ReturnsTheIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of  false values in the list.
        /// </summary>
        public static string ReturnsTheNumberOfFalseValueInList {
            get {
                return ResourceManager.GetString("ReturnsTheNumberOfFalseValueInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of true values in the list.
        /// </summary>
        public static string ReturnsTheNumberOfTrueValue {
            get {
                return ResourceManager.GetString("ReturnsTheNumberOfTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;;&apos; is expected.
        /// </summary>
        public static string SemiColonExpected {
            get {
                return ResourceManager.GetString("SemiColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/&quot; expected.
        /// </summary>
        public static string SlashExpected {
            get {
                return ResourceManager.GetString("SlashExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorts a specified list by the values of its members in either ascending or descending order.
        /// </summary>
        public static string SortsListByValue {
            get {
                return ResourceManager.GetString("SortsListByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorts a specified list by values of its members in ascending order.
        /// </summary>
        public static string SortsListByValueInAscending {
            get {
                return ResourceManager.GetString("SortsListByValueInAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textstring expected.
        /// </summary>
        public static string textstring_expected {
            get {
                return ResourceManager.GetString("textstring_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this symbol not expected in Associative_FunctionalStatement.
        /// </summary>
        public static string ThisSymbolNotExpectedInAssociativeFunctionalStatement {
            get {
                return ResourceManager.GetString("ThisSymbolNotExpectedInAssociativeFunctionalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this symbol not expected in Associative_FunctionCallStatement.
        /// </summary>
        public static string ThisSymbolNotExpectedInAssociativeFunctionCallStatement {
            get {
                return ResourceManager.GetString("ThisSymbolNotExpectedInAssociativeFunctionCallStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this symbol not expected in Associative_NonAssignmentStatement.
        /// </summary>
        public static string ThisSymbolNotExpectedInAssociativeNonAssignmentStatement {
            get {
                return ResourceManager.GetString("ThisSymbolNotExpectedInAssociativeNonAssignmentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this symbol not expected in Associative_Statement.
        /// </summary>
        public static string ThisSymbolNotExpectedInAssociativeStatement {
            get {
                return ResourceManager.GetString("ThisSymbolNotExpectedInAssociativeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this symbol not expected in Import_Statement.
        /// </summary>
        public static string ThisSymbolNotExpectedInImportStatement {
            get {
                return ResourceManager.GetString("ThisSymbolNotExpectedInImportStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;throw&quot; expected.
        /// </summary>
        public static string ThrowExpected {
            get {
                return ResourceManager.GetString("ThrowExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters in character literal.
        /// </summary>
        public static string TooManyCharacters {
            get {
                return ResourceManager.GetString("TooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;try&quot; expected.
        /// </summary>
        public static string TryExpected {
            get {
                return ResourceManager.GetString("TryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown attribute {0}.
        /// </summary>
        public static string UnknownAttribute {
            get {
                return ResourceManager.GetString("UnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; statement can only be used in imperative language block, consider using an inline conditional instead?.
        /// </summary>
        public static string UseInlineConditional {
            get {
                return ResourceManager.GetString("UseInlineConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use List.Join node instead.
        /// </summary>
        public static string UseListJoinNode {
            get {
                return ResourceManager.GetString("UseListJoinNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; statement can only be used in imperative language block.
        /// </summary>
        public static string ValidForImperativeBlockOnly {
            get {
                return ResourceManager.GetString("ValidForImperativeBlockOnly", resourceCulture);
            }
        }
    }
}
