//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeometryUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeometryUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the given geometry to the given SAT file path.
        /// </summary>
        public static string ExportToSATDescripiton {
            get {
                return ResourceManager.GetString("ExportToSATDescripiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to export the geometry to..
        /// </summary>
        public static string ExportToSatFilePathDescription {
            get {
                return ResourceManager.GetString("ExportToSatFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path of the exported file. Note this may change from the input in it contains non-ASCII characters..
        /// </summary>
        public static string ExportToSatFilePathOutputDescription {
            get {
                return ResourceManager.GetString("ExportToSatFilePathOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry to export into a SAT file..
        /// </summary>
        public static string ExportToSatGeometryInputDescription {
            get {
                return ResourceManager.GetString("ExportToSatGeometryInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export;SAT.
        /// </summary>
        public static string ExportWithUnitsSearchTags {
            get {
                return ResourceManager.GetString("ExportWithUnitsSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAB byte array..
        /// </summary>
        public static string ImportSABByteArrayDesc {
            get {
                return ResourceManager.GetString("ImportSABByteArrayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A forge unit length, if left null, geometry will be imported as unitless..
        /// </summary>
        public static string ImportSATDynamoUnitDesc {
            get {
                return ResourceManager.GetString("ImportSATDynamoUnitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filepath or File object to import .SAT from..
        /// </summary>
        public static string ImportSATFilePathDesc {
            get {
                return ResourceManager.GetString("ImportSATFilePathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports geometry from SAB byte array. Set the dynamoUnit input to match how you are interpreting the other numbers in your Dynamo file..
        /// </summary>
        public static string ImportToSABUnitsDesc {
            get {
                return ResourceManager.GetString("ImportToSABUnitsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports geometry from SAT filepath. Set the dynamoUnit input to match how you are interpreting the other numbers in your Dynamo file..
        /// </summary>
        public static string ImportToSATUnitsDesc {
            get {
                return ResourceManager.GetString("ImportToSATUnitsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A drop down node that allow easy access to PanelSurface BoundaryCondition possible values.
        /// </summary>
        public static string PanelSurfaceBoundaryConditionDropDownDesc {
            get {
                return ResourceManager.GetString("PanelSurfaceBoundaryConditionDropDownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded geometry.
        /// </summary>
        public static string SABSATGeoDesc {
            get {
                return ResourceManager.GetString("SABSATGeoDesc", resourceCulture);
            }
        }
    }
}
