version: 0.1.1
env:
  - BUILD_MACHINE: "Dynamo_Win_Perf"
  
check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true
language: csharp

nuget_config:
  config_file: dynamo-nuget.config
  custom_feeds:
    - "team-dynamo-nuget"
    - "autodesk3p"

build:
  scripts:
    - "powershell.exe -ExecutionPolicy ByPass -File .\\DockerUtilities\\PreBuildScript.ps1"

code_analysis:
  sonarqube:
   useCommonSonar: true
   msbuildCommands:
      - ".\src\buildDyn.cmd"

