//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSCoreNodesUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSCoreNodesUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean AND: Returns true only if both of the inputs are true. If either is false, returns false..
        /// </summary>
        internal static string AndDescription {
            get {
                return ResourceManager.GetString("AndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of application..
        /// </summary>
        internal static string ApplyPortDataFuncArgToolTip {
            get {
                return ResourceManager.GetString("ApplyPortDataFuncArgToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function to apply..
        /// </summary>
        internal static string ApplyPortDataFuncToolTip {
            get {
                return ResourceManager.GetString("ApplyPortDataFuncToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection between a true and false..
        /// </summary>
        internal static string BooleanDescription {
            get {
                return ResourceManager.GetString("BooleanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true;truth;false.
        /// </summary>
        internal static string BooleanSelectorSearchTags {
            get {
                return ResourceManager.GetString("BooleanSelectorSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a color given a color range..
        /// </summary>
        internal static string ColorRangeDescription {
            get {
                return ResourceManager.GetString("ColorRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of colors to include in the range..
        /// </summary>
        internal static string ColorRangePortDataColorsToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataColorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of values between 0.0 and 1.0 which position the input colors along the range..
        /// </summary>
        internal static string ColorRangePortDataIndicesToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataIndicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected colors..
        /// </summary>
        internal static string ColorRangePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of values between 0.0 and 1.0. These values are used to look up the color within the range..
        /// </summary>
        internal static string ColorRangePortDataValueToolTip {
            get {
                return ResourceManager.GetString("ColorRangePortDataValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinator.
        /// </summary>
        internal static string CombinatorPortDataCombToolTip {
            get {
                return ResourceManager.GetString("CombinatorPortDataCombToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined lists.
        /// </summary>
        internal static string CombinatorPortDataResultToolTip {
            get {
                return ResourceManager.GetString("CombinatorPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function #0.
        /// </summary>
        internal static string ComposePortDataFunc0ToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataFunc0ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function #1.
        /// </summary>
        internal static string ComposePortDataFunc1ToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataFunc1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed function..
        /// </summary>
        internal static string ComposePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ComposePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert between units of measure..
        /// </summary>
        internal static string ConversionNodeDescription {
            get {
                return ResourceManager.GetString("ConversionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Index #0.
        /// </summary>
        internal static string CreateListPortDataIndex0ToolTip {
            get {
                return ResourceManager.GetString("CreateListPortDataIndex0ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list.
        /// </summary>
        internal static string CreateListPortDataResultToolTip {
            get {
                return ResourceManager.GetString("CreateListPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a directory object from a path..
        /// </summary>
        internal static string DirectoryFromPathDescription {
            get {
                return ResourceManager.GetString("DirectoryFromPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to select a directory on the system to get its path.
        /// </summary>
        internal static string DirectoryNodeDescription {
            get {
                return ResourceManager.GetString("DirectoryNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a directory object from a path.
        /// </summary>
        internal static string DirectoryObjectNodeDescription {
            get {
                return ResourceManager.GetString("DirectoryObjectNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the directory..
        /// </summary>
        internal static string DirectoryObjectPortDataPathToolTip {
            get {
                return ResourceManager.GetString("DirectoryObjectPortDataPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory object..
        /// </summary>
        internal static string DirectoryObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("DirectoryObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to select a directory on the system to get its path..
        /// </summary>
        internal static string DirectoryPathDescription {
            get {
                return ResourceManager.GetString("DirectoryPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a number..
        /// </summary>
        internal static string DoubleInputNodeDescription {
            get {
                return ResourceManager.GetString("DoubleInputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slider that produces double values..
        /// </summary>
        internal static string DoubleSliderDescription {
            get {
                return ResourceManager.GetString("DoubleSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slider that produces numeric values..
        /// </summary>
        internal static string DoubleSliderNodeDescription {
            get {
                return ResourceManager.GetString("DoubleSliderNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double;number;float;integer;slider.
        /// </summary>
        internal static string DoubleSliderSearchTags {
            get {
                return ResourceManager.GetString("DoubleSliderSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected {0}.
        /// </summary>
        internal static string DropDownPortDataResultToolTip {
            get {
                return ResourceManager.GetString("DropDownPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert;Units;Length;Area;Volume.
        /// </summary>
        internal static string DynamoConvertSearchTags {
            get {
                return ResourceManager.GetString("DynamoConvertSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a file object from a path..
        /// </summary>
        internal static string FileFromPathDescription {
            get {
                return ResourceManager.GetString("FileFromPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to select a file on the system to get its filename.
        /// </summary>
        internal static string FilenameNodeDescription {
            get {
                return ResourceManager.GetString("FilenameNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a file object from a path..
        /// </summary>
        internal static string FileObjectNodeDescription {
            get {
                return ResourceManager.GetString("FileObjectNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the file..
        /// </summary>
        internal static string FileObjectPortDataPathToolTip {
            get {
                return ResourceManager.GetString("FileObjectPortDataPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File object.
        /// </summary>
        internal static string FileObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FileObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to select a file on the system to get its filename..
        /// </summary>
        internal static string FilePathDescription {
            get {
                return ResourceManager.GetString("FilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate used to determine if an element is filtered in or out..
        /// </summary>
        internal static string FilterPortDataConditionToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataConditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List to filter.
        /// </summary>
        internal static string FilterPortDataListToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List containing all elements &quot;x&quot; where condition(x) = True.
        /// </summary>
        internal static string FilterPortDataResultInToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataResultInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List containing all elements &quot;x&quot; where condition(x) = False.
        /// </summary>
        internal static string FilterPortDataResultOutToolTip {
            get {
                return ResourceManager.GetString("FilterPortDataResultOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluates mathematical formulas. Uses NCalc: http://ncalc.codeplex.com/.
        /// </summary>
        internal static string FormulaDescription {
            get {
                return ResourceManager.GetString("FormulaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of math computation.
        /// </summary>
        internal static string FormulaPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FormulaPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array of object to be serialized.
        /// </summary>
        internal static string FromArrayPortDataArrayToolTip {
            get {
                return ResourceManager.GetString("FromArrayPortDataArrayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String representation of the array.
        /// </summary>
        internal static string FromArrayPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FromArrayPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.fromarray;tostring;2string;list2string;listtostring;array2string;arraytostring.
        /// </summary>
        internal static string FromArraySearchTags {
            get {
                return ResourceManager.GetString("FromArraySearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to be serialized.
        /// </summary>
        internal static string FromObjectPortDataObjToolTip {
            get {
                return ResourceManager.GetString("FromObjectPortDataObjToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String representation of the object.
        /// </summary>
        internal static string FromObjectPortDataResultToolTip {
            get {
                return ResourceManager.GetString("FromObjectPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.fromobject;tostring;2string;number2string;numbertostring.
        /// </summary>
        internal static string FromObjectSearchTags {
            get {
                return ResourceManager.GetString("FromObjectSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a function to arguments..
        /// </summary>
        internal static string FunctionApplyDescription {
            get {
                return ResourceManager.GetString("FunctionApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose multiple functions..
        /// </summary>
        internal static string FunctionComposeDescription {
            get {
                return ResourceManager.GetString("FunctionComposeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional statement.
        /// </summary>
        internal static string IfDescription {
            get {
                return ResourceManager.GetString("IfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slider that produces integer values..
        /// </summary>
        internal static string IntegerSliderDescription {
            get {
                return ResourceManager.GetString("IntegerSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slider that produces integer values..
        /// </summary>
        internal static string IntegerSliderNodeDescription {
            get {
                return ResourceManager.GetString("IntegerSliderNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an obsolete node.
        /// </summary>
        internal static string LegacyNodeDescription {
            get {
                return ResourceManager.GetString("LegacyNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a combinator to each pair in the cartesian product of two sequences.
        /// </summary>
        internal static string ListCartesianProductDescription {
            get {
                return ResourceManager.GetString("ListCartesianProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cross product;crossreference;cross ref;.
        /// </summary>
        internal static string ListCartesianProductSearchTags {
            get {
                return ResourceManager.GetString("ListCartesianProductSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a combinator to each element in two sequences.
        /// </summary>
        internal static string ListCombineDescription {
            get {
                return ResourceManager.GetString("ListCombineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map multiple;apply over lists;multiple inputs.
        /// </summary>
        internal static string ListCombineSearchTags {
            get {
                return ResourceManager.GetString("ListCombineSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes a new list out of the given inputs.
        /// </summary>
        internal static string ListCreateDescription {
            get {
                return ResourceManager.GetString("ListCreateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entwine;listcreate,newlist;makelist;list;.
        /// </summary>
        internal static string ListCreateSearchTags {
            get {
                return ResourceManager.GetString("ListCreateSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters a sequence by a given condition such that for an arbitrary element &quot;x,&quot; condition(x) = True or False..
        /// </summary>
        internal static string ListFilterDescription {
            get {
                return ResourceManager.GetString("ListFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen;dispatch;.
        /// </summary>
        internal static string ListFilterSearchTags {
            get {
                return ResourceManager.GetString("ListFilterSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs a computation on each element of a list. Does not accumulate results..
        /// </summary>
        internal static string ListForEachDescription {
            get {
                return ResourceManager.GetString("ListForEachDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply function;void;.
        /// </summary>
        internal static string ListForEachSearchTags {
            get {
                return ResourceManager.GetString("ListForEachSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a combinator to each pair resulting from a longest lacing of the input lists. All lists have their last element repeated to match the length of the longest input..
        /// </summary>
        internal static string ListLaceLongestDescription {
            get {
                return ResourceManager.GetString("ListLaceLongestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat last;.
        /// </summary>
        internal static string ListLaceLongestSearchTags {
            get {
                return ResourceManager.GetString("ListLaceLongestSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a combinator to each pair resulting from a shortest lacing of the input lists. All lists are truncated to the length of the shortest input..
        /// </summary>
        internal static string ListLaceShortestDescription {
            get {
                return ResourceManager.GetString("ListLaceShortestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mix;trim end.
        /// </summary>
        internal static string ListLaceShortestSearchTags {
            get {
                return ResourceManager.GetString("ListLaceShortestSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a function over all elements of a list, generating a new list from the results..
        /// </summary>
        internal static string ListMapDescription {
            get {
                return ResourceManager.GetString("ListMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function;applied;over list;do to each.
        /// </summary>
        internal static string ListMapSearchTags {
            get {
                return ResourceManager.GetString("ListMapSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces a list into a new value by combining each element with an accumulated result..
        /// </summary>
        internal static string ListReduceDescription {
            get {
                return ResourceManager.GetString("ListReduceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accumulate;aggregate;fold.
        /// </summary>
        internal static string ListReduceSearchTags {
            get {
                return ResourceManager.GetString("ListReduceSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces a list into a new value by combining each element with an accumulated result, produces a list of successive reduced values..
        /// </summary>
        internal static string ListScanDescription {
            get {
                return ResourceManager.GetString("ListScanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intermediate;maps;folds.
        /// </summary>
        internal static string ListScanSearchTags {
            get {
                return ResourceManager.GetString("ListScanSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure used to map element.
        /// </summary>
        internal static string MapPortDataFxToolTip {
            get {
                return ResourceManager.GetString("MapPortDataFxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list to map over..
        /// </summary>
        internal static string MapPortDataListToolTip {
            get {
                return ResourceManager.GetString("MapPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped list.
        /// </summary>
        internal static string MapPortDataResultToolTip {
            get {
                return ResourceManager.GetString("MapPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a sequence of numbers in the specified range..
        /// </summary>
        internal static string NumberRangeDescription {
            get {
                return ResourceManager.GetString("NumberRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a sequence of numbers..
        /// </summary>
        internal static string NumberSequenceDescription {
            get {
                return ResourceManager.GetString("NumberSequenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean OR: Returns true if either of the inputs are true. If neither are true, returns false..
        /// </summary>
        internal static string OrDescription {
            get {
                return ResourceManager.GetString("OrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False block.
        /// </summary>
        internal static string PortDataFalseBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataFalseBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string PortDataImageToolTip {
            get {
                return ResourceManager.GetString("PortDataImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List #1.
        /// </summary>
        internal static string PortDataList1ToolTip {
            get {
                return ResourceManager.GetString("PortDataList1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List #2.
        /// </summary>
        internal static string PortDataList2ToolTip {
            get {
                return ResourceManager.GetString("PortDataList2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operand.
        /// </summary>
        internal static string PortDataOperandToolTip {
            get {
                return ResourceManager.GetString("PortDataOperandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        internal static string PortDataResultToolTip {
            get {
                return ResourceManager.GetString("PortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test block.
        /// </summary>
        internal static string PortDataTestBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataTestBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True block.
        /// </summary>
        internal static string PortDataTrueBlockToolTip {
            get {
                return ResourceManager.GetString("PortDataTrueBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string PortDataVariableToolTip {
            get {
                return ResourceManager.GetString("PortDataVariableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reductor Function: accepts one item from each list being reduced, and the current accumulated value, result is the new accumulated value..
        /// </summary>
        internal static string ReducePortDataReductorToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataReductorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced lists.
        /// </summary>
        internal static string ReducePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting accumulated value, to be passed into the first call to the Reductor function..
        /// </summary>
        internal static string ReducePortDataSeedToolTip {
            get {
                return ResourceManager.GetString("ReducePortDataSeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces an object with a given substitute if the original object satisfies a given condition..
        /// </summary>
        internal static string ReplaceByConditionDescription {
            get {
                return ResourceManager.GetString("ReplaceByConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicate;override;replace if,.
        /// </summary>
        internal static string ReplaceByConditionSearchTags {
            get {
                return ResourceManager.GetString("ReplaceByConditionSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate used to determine if it should be replaced..
        /// </summary>
        internal static string ReplacePortDataConditionToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataConditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to potentially be replaced.
        /// </summary>
        internal static string ReplacePortDataItemToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to replace with.
        /// </summary>
        internal static string ReplacePortDataReplaceWithToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataReplaceWithToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If condition(item) = True, then &quot;replaceWith&quot; is returned. Otherwise &quot;item&quot; is returned unaltered..
        /// </summary>
        internal static string ReplacePortDataResultToolTip {
            get {
                return ResourceManager.GetString("ReplacePortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reductor Function: accepts one item from each list being reduced, and the current accumulated value, result is the new accumulated value..
        /// </summary>
        internal static string ScanPortDataReductorToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataReductorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned lists.
        /// </summary>
        internal static string ScanPortDataResultToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting accumulated value, to be passed into the first call to the Reductor function..
        /// </summary>
        internal static string ScanPortDataSeedToolTip {
            get {
                return ResourceManager.GetString("ScanPortDataSeedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoped If statement.
        /// </summary>
        internal static string ScopeIfDescription {
            get {
                return ResourceManager.GetString("ScopeIfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your Revit display unit settings.
        /// </summary>
        internal static string SelectFromComboBoxToolTip {
            get {
                return ResourceManager.GetString("SelectFromComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected elements..
        /// </summary>
        internal static string SelectionPortDataResultToolTip {
            get {
                return ResourceManager.GetString("SelectionPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert an array to a string representation..
        /// </summary>
        internal static string StringfromArrayDescription {
            get {
                return ResourceManager.GetString("StringfromArrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert an object to a string representation..
        /// </summary>
        internal static string StringfromObjectDescription {
            get {
                return ResourceManager.GetString("StringfromObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a string..
        /// </summary>
        internal static string StringInputNodeDescription {
            get {
                return ResourceManager.GetString("StringInputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize the output of node..
        /// </summary>
        internal static string WatchDescription {
            get {
                return ResourceManager.GetString("WatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previews an image.
        /// </summary>
        internal static string WatchImageDescription {
            get {
                return ResourceManager.GetString("WatchImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image;inspect image;pixels;display;panel;.
        /// </summary>
        internal static string WatchImageSearchTags {
            get {
                return ResourceManager.GetString("WatchImageSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize the output of node..
        /// </summary>
        internal static string WatchNodeDescription {
            get {
                return ResourceManager.GetString("WatchNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print;output;disply;panel;inspect;debug.
        /// </summary>
        internal static string WatchNodeSearchTags {
            get {
                return ResourceManager.GetString("WatchNodeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node to evaluate..
        /// </summary>
        internal static string WatchPortDataInputToolTip {
            get {
                return ResourceManager.GetString("WatchPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch contents..
        /// </summary>
        internal static string WatchPortDataResultToolTip {
            get {
                return ResourceManager.GetString("WatchPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print;output;display.
        /// </summary>
        internal static string WatchSearchTags {
            get {
                return ResourceManager.GetString("WatchSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a web request given a url..
        /// </summary>
        internal static string WebRequestDescription {
            get {
                return ResourceManager.GetString("WebRequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the web request..
        /// </summary>
        internal static string WebRequestPortDataResultToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url for the web request..
        /// </summary>
        internal static string WebRequestPortDataUrlToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataUrlToolTip", resourceCulture);
            }
        }
    }
}
