//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.GraphMetadata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.GraphMetadata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Property.
        /// </summary>
        public static string CustomPropertyControl_CustomPropertyDefault {
            get {
                return ResourceManager.GetString("CustomPropertyControl_CustomPropertyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string GraphMetaData_AuthorName {
            get {
                return ResourceManager.GetString("GraphMetaData_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Properties.
        /// </summary>
        public static string GraphMetaData_CustomProperties {
            get {
                return ResourceManager.GetString("GraphMetaData_CustomProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GraphMetaData_Description {
            get {
                return ResourceManager.GetString("GraphMetaData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Type.
        /// </summary>
        public static string GraphMetaData_GraphType {
            get {
                return ResourceManager.GetString("GraphMetaData_GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string GraphMetaData_Image {
            get {
                return ResourceManager.GetString("GraphMetaData_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More URL.
        /// </summary>
        public static string GraphMetaData_LearnMoreURL {
            get {
                return ResourceManager.GetString("GraphMetaData_LearnMoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop or Select image.
        /// </summary>
        public static string ImageSelector_Message_DefaultFeedback {
            get {
                return ResourceManager.GetString("ImageSelector_Message_DefaultFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your image.
        /// </summary>
        public static string ImageSelector_Message_DropImage {
            get {
                return ResourceManager.GetString("ImageSelector_Message_DropImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only image files are allowed.
        /// </summary>
        public static string ImageSelector_Message_InvalidExtension {
            get {
                return ResourceManager.GetString("ImageSelector_Message_InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image selected.
        /// </summary>
        public static string ImageSelector_Message_NoImageSelected {
            get {
                return ResourceManager.GetString("ImageSelector_Message_NoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string ImageSelector_Title_SelectImage {
            get {
                return ResourceManager.GetString("ImageSelector_Title_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Graph _Properties.
        /// </summary>
        public static string MenuItemText {
            get {
                return ResourceManager.GetString("MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not a valid URI.
        /// </summary>
        public static string URIValidationRule_Fail_Message {
            get {
                return ResourceManager.GetString("URIValidationRule_Fail_Message", resourceCulture);
            }
        }
    }
}
