//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrrrg, ok.
        /// </summary>
        public static string ArggOKButton {
            get {
                return ResourceManager.GetString("ArggOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null.
        ///Parameter name: {0}.
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        public static string Autocomplete {
            get {
                return ResourceManager.GetString("Autocomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All recommendations are below the specified confidence level. You can try them or adjust the confidence settings in Preferences..
        /// </summary>
        public static string AutocompleteLowConfidenceMessage {
            get {
                return ResourceManager.GetString("AutocompleteLowConfidenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low confidence.
        /// </summary>
        public static string AutocompleteLowConfidenceTitle {
            get {
                return ResourceManager.GetString("AutocompleteLowConfidenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Recommendations that are below the confidence level..
        /// </summary>
        public static string AutocompleteLowConfidenceTooltip {
            get {
                return ResourceManager.GetString("AutocompleteLowConfidenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recommendations yet. You can try switching to node type match autocomplete..
        /// </summary>
        public static string AutocompleteNoRecommendationsMessage {
            get {
                return ResourceManager.GetString("AutocompleteNoRecommendationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recommendations.
        /// </summary>
        public static string AutocompleteNoRecommendationsTitle {
            get {
                return ResourceManager.GetString("AutocompleteNoRecommendationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Autocomplete Results.
        /// </summary>
        public static string AutocompleteSearchTextBlockText {
            get {
                return ResourceManager.GetString("AutocompleteSearchTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file &apos;{0}&apos; gets backed up at &apos;{1}&apos;.
        /// </summary>
        public static string BackUpOriginalFileMessage {
            get {
                return ResourceManager.GetString("BackUpOriginalFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file is saved.
        /// </summary>
        public static string BackupSavedMsg {
            get {
                return ResourceManager.GetString("BackupSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad identifier syntax: &quot;{0}&quot;.
        /// </summary>
        public static string BadIdentifierSyntax {
            get {
                return ResourceManager.GetString("BadIdentifierSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad range syntax: not of format \&quot;start..end[..(increment|#count)]\&quot;.
        /// </summary>
        public static string BadRangeSyntax {
            get {
                return ResourceManager.GetString("BadRangeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build sublists from a list using DesignScript range syntax..
        /// </summary>
        public static string BuildSublistsDescription {
            get {
                return ResourceManager.GetString("BuildSublistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest version.
        /// </summary>
        public static string ButtonDownloadLastest {
            get {
                return ResourceManager.GetString("ButtonDownloadLastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed anyway.
        /// </summary>
        public static string ButtonProcess {
            get {
                return ResourceManager.GetString("ButtonProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t have 0 step..
        /// </summary>
        public static string CannotHave0Step {
            get {
                return ResourceManager.GetString("CannotHave0Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file cannot be opened.
        /// </summary>
        public static string CannotOpenFile {
            get {
                return ResourceManager.GetString("CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing workflow....
        /// </summary>
        public static string ClearingWorkflow {
            get {
                return ResourceManager.GetString("ClearingWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing workspace....
        /// </summary>
        public static string ClearingWorkSpace {
            get {
                return ResourceManager.GetString("ClearingWorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for DesignScript code to be authored directly.
        /// </summary>
        public static string CodeBlockDescription {
            get {
                return ResourceManager.GetString("CodeBlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for DesignScript code to be authored directly.
        /// </summary>
        public static string CodeBlockNodeDescription {
            get {
                return ResourceManager.GetString("CodeBlockNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codeblock;.
        /// </summary>
        public static string CodeBlockSearchTags {
            get {
                return ResourceManager.GetString("CodeBlockSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of expression at line {0}.
        /// </summary>
        public static string CodeBlockTempIdentifierOutputLabel {
            get {
                return ResourceManager.GetString("CodeBlockTempIdentifierOutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composes two single parameter functions into one function..
        /// </summary>
        public static string ComposeFunctionNodeDescription {
            get {
                return ResourceManager.GetString("ComposeFunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Function.
        /// </summary>
        public static string ComposeFunctionPortDataFunctionToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataFunctionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed function: g(f(x)).
        /// </summary>
        public static string ComposeFunctionPortDataResultToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This assembly is likely blocked. Try restarting Dynamo after unblocking this assembly and all other core assemblies that might be blocked. If you are running a downloaded DynamoSandbox build that is extracted from a .zip file, try using 7zip to extract the Dynamo binaries and try again..
        /// </summary>
        public static string CoreLibraryLoadFailureForBlockedAssembly {
            get {
                return ResourceManager.GetString("CoreLibraryLoadFailureForBlockedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core library load failure.
        /// </summary>
        public static string CoreLibraryLoadFailureMessageBoxTitle {
            get {
                return ResourceManager.GetString("CoreLibraryLoadFailureMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compress file.  Is the file in use?.
        /// </summary>
        public static string CouldNotCompressFile {
            get {
                return ResourceManager.GetString("CouldNotCompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the latest build from S3.
        /// </summary>
        public static string CouldNotGetLatestBuild {
            get {
                return ResourceManager.GetString("CouldNotGetLatestBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get update data from {0}.
        /// </summary>
        public static string CouldNotGetUpdateData {
            get {
                return ResourceManager.GetString("CouldNotGetUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load types..
        /// </summary>
        public static string CouldNotLoadTypes {
            get {
                return ResourceManager.GetString("CouldNotLoadTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not repair 1-node holes.
        /// </summary>
        public static string CouldNotRepairOneNodeHoles {
            get {
                return ResourceManager.GetString("CouldNotRepairOneNodeHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : Could not create connector between {0} and {1}..
        /// </summary>
        public static string CreatingConnectorError {
            get {
                return ResourceManager.GetString("CreatingConnectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom node \&quot;{0}\&quot; could not be initialized..
        /// </summary>
        public static string CustomNodeCouldNotBeInitialized {
            get {
                return ResourceManager.GetString("CustomNodeCouldNotBeInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of a Custom Node.
        /// </summary>
        public static string CustomNodeDesciption {
            get {
                return ResourceManager.GetString("CustomNodeDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load custom node directory. Do you have permission to access {0}?.
        /// </summary>
        public static string CustomNodeFolderLoadFailure {
            get {
                return ResourceManager.GetString("CustomNodeFolderLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom node definition is not loaded! href=CustomNodeNotLoaded.html.
        /// </summary>
        public static string CustomNodeNotLoaded {
            get {
                return ResourceManager.GetString("CustomNodeNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom nodes.
        /// </summary>
        public static string DefaultCustomNodeCategory {
            get {
                return ResourceManager.GetString("DefaultCustomNodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string DefaultHomeWorkspaceName {
            get {
                return ResourceManager.GetString("DefaultHomeWorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (disabled).
        /// </summary>
        public static string DefaultValueDisabled {
            get {
                return ResourceManager.GetString("DefaultValueDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some description.
        /// </summary>
        public static string DescriptionResource1 {
            get {
                return ResourceManager.GetString("DescriptionResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found : {0}.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The virtual machine that powers Dynamo is experiencing some unexpected errors internally and is likely having great difficulties pulling itself together. It is recommended that you save your work now and reload the file. Giving the Dynamo VM a new lease of life can potentially make it feel happier and behave better. 
        ///
        ///If you don&apos;t mind, it would be helpful for you to send us your file. That will make it quicker for us to get these issues fixed..
        /// </summary>
        public static string DisplayEngineFailureMessageDescription {
            get {
                return ResourceManager.GetString("DisplayEngineFailureMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dll Load Exception:.
        /// </summary>
        public static string DllLoadException {
            get {
                return ResourceManager.GetString("DllLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest version.
        /// </summary>
        public static string DownloadLatestButton {
            get {
                return ResourceManager.GetString("DownloadLatestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignScript Builtin Functions.
        /// </summary>
        public static string DSFunctionNodeDescription {
            get {
                return ResourceManager.GetString("DSFunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate of the package called {0} was found at {1}.  Ignoring it..
        /// </summary>
        public static string DulicatedPackage {
            get {
                return ResourceManager.GetString("DulicatedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an obsolete node.
        /// </summary>
        public static string DummyNodeDescription {
            get {
                return ResourceManager.GetString("DummyNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map already contains a model with this id, the id must be unique for the workspace that is currently being deserialized: {0}.
        /// </summary>
        public static string DuplicatedModelGuidError {
            get {
                return ResourceManager.GetString("DuplicatedModelGuidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of the package called {0} version {2} was found at {1} with version {3}. The newer version has been ignored..
        /// </summary>
        public static string DuplicatedNewerPackage {
            get {
                return ResourceManager.GetString("DuplicatedNewerPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An older version of the package called {0} version {2} was found at {1} with version {3}. The older version has been ignored..
        /// </summary>
        public static string DuplicatedOlderPackage {
            get {
                return ResourceManager.GetString("DuplicatedOlderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate migration type registered for {0}.
        /// </summary>
        public static string DuplicateMigrationTypeRegistered {
            get {
                return ResourceManager.GetString("DuplicateMigrationTypeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English,Čeština,Deutsch,Español,Français,Italiano,日本語,한국어,Polski,Português (Brasil),Русский,简体中文,繁體中文.
        /// </summary>
        public static string DynamoLanguages_noxlate {
            get {
                return ResourceManager.GetString("DynamoLanguages_noxlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo is up to date..
        /// </summary>
        public static string DynamoUpToDate {
            get {
                return ResourceManager.GetString("DynamoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} elapsed for loading xml..
        /// </summary>
        public static string ElapsedWhenLoadingXml {
            get {
                return ResourceManager.GetString("ElapsedWhenLoadingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation completed in {0}.
        /// </summary>
        public static string EvaluationCompleted {
            get {
                return ResourceManager.GetString("EvaluationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered scanning the package directory at {0}.
        /// </summary>
        public static string ExceptionEncountered {
            get {
                return ResourceManager.GetString("ExceptionEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the file as some of the nodes already exist in the current worspace..
        /// </summary>
        public static string FailedInsertFileNodeExistNotification {
            get {
                return ResourceManager.GetString("FailedInsertFileNodeExistNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get mirror for variable:  {0}; reason: {1}..
        /// </summary>
        public static string FailedToGetMirrorVariable {
            get {
                return ResourceManager.GetString("FailedToGetMirrorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call Ready() in extension: .
        /// </summary>
        public static string FailedToHandleReadyEvent {
            get {
                return ResourceManager.GetString("FailedToHandleReadyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}\n, Exception: {1}.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load custom node: {0}.  Replacing with proxy custom node..
        /// </summary>
        public static string FailedToLoadCustomNode {
            get {
                return ResourceManager.GetString("FailedToLoadCustomNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The header for the custom node at {0} failed to load.  It will be left out of search..
        /// </summary>
        public static string FailedToLoadHeader {
            get {
                return ResourceManager.GetString("FailedToLoadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load library: {0}.
        /// </summary>
        public static string FailedToLoadLibrary {
            get {
                return ResourceManager.GetString("FailedToLoadLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load type from {0}. The type was {1}..
        /// </summary>
        public static string FailedToLoadType {
            get {
                return ResourceManager.GetString("FailedToLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save {0}\n, Exception: {1}.
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file &apos;{0}&apos; gets backed up at &apos;{1}&apos;.
        /// </summary>
        public static string FileBackUpLocation {
            get {
                return ResourceManager.GetString("FileBackUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file cannot be opened..
        /// </summary>
        public static string FileCannotBeOpened {
            get {
                return ResourceManager.GetString("FileCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File load failure.
        /// </summary>
        public static string FileLoadFailureMessageBoxTitle {
            get {
                return ResourceManager.GetString("FileLoadFailureMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file may not open correctly.
        /// </summary>
        public static string FileNotOpenedCorrectly {
            get {
                return ResourceManager.GetString("FileNotOpenedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load customNode {0} loaded by package {1}, but a previous definition named {2} exists with no associated package. The new customNode definition has been loaded, but Dynamo may be in an unstable state, please avoid loading multiple custom nodes with the id..
        /// </summary>
        public static string FunctionDefinitionOverwrittenMessage {
            get {
                return ResourceManager.GetString("FunctionDefinitionOverwrittenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of a Custom Node.
        /// </summary>
        public static string FunctionDescription {
            get {
                return ResourceManager.GetString("FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignScript Builtin Functions.
        /// </summary>
        public static string FunctionNodeDescription {
            get {
                return ResourceManager.GetString("FunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file &apos;{0}&apos; was created in future version &apos;{1}&apos; and may not open correctly in your installed version of Dynamo &apos;{2}&apos;.
        /// </summary>
        public static string FutureFileDescription {
            get {
                return ResourceManager.GetString("FutureFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file may not open correctly.
        /// </summary>
        public static string FutureFileSummary {
            get {
                return ResourceManager.GetString("FutureFileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future File.
        /// </summary>
        public static string FutureFileTitle {
            get {
                return ResourceManager.GetString("FutureFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        public static string GoodByeLog {
            get {
                return ResourceManager.GetString("GoodByeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Double click here to edit group description&gt;.
        /// </summary>
        public static string GroupDefaultText {
            get {
                return ResourceManager.GetString("GroupDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Double click here to edit group title&gt;.
        /// </summary>
        public static string GroupNameDefaultText {
            get {
                return ResourceManager.GetString("GroupNameDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string GroupStyleDefaultActions {
            get {
                return ResourceManager.GetString("GroupStyleDefaultActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B9F9E1.
        /// </summary>
        public static string GroupStyleDefaultActionsColor {
            get {
                return ResourceManager.GetString("GroupStyleDefaultActionsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string GroupStyleDefaultInputs {
            get {
                return ResourceManager.GetString("GroupStyleDefaultInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFB8D8.
        /// </summary>
        public static string GroupStyleDefaultInputsColor {
            get {
                return ResourceManager.GetString("GroupStyleDefaultInputsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string GroupStyleDefaultOutputs {
            get {
                return ResourceManager.GetString("GroupStyleDefaultOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFC999.
        /// </summary>
        public static string GroupStyleDefaultOutputsColor {
            get {
                return ResourceManager.GetString("GroupStyleDefaultOutputsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string GroupStyleDefaultReview {
            get {
                return ResourceManager.GetString("GroupStyleDefaultReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4E1FF.
        /// </summary>
        public static string GroupStyleDefaultReviewColor {
            get {
                return ResourceManager.GetString("GroupStyleDefaultReviewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string HeaderAction {
            get {
                return ResourceManager.GetString("HeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string HeaderCreate {
            get {
                return ResourceManager.GetString("HeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUERY.
        /// </summary>
        public static string HeaderQuery {
            get {
                return ResourceManager.GetString("HeaderQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No identifiers found..
        /// </summary>
        public static string IdentifiersNotFound {
            get {
                return ResourceManager.GetString("IdentifiersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file &apos;{0}&apos; of version &apos;{1}&apos; cannot be opened by this version of Dynamo ({2}).
        /// </summary>
        public static string IncompatibleOfFileAndDynamo {
            get {
                return ResourceManager.GetString("IncompatibleOfFileAndDynamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the incorrectly formatted library name:.
        /// </summary>
        public static string IncorrectlyFormattedNodeLibraryDisplay {
            get {
                return ResourceManager.GetString("IncorrectlyFormattedNodeLibraryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrectly formatted package node library encountered, this may result in a package assembly not being loaded!.
        /// </summary>
        public static string IncorrectlyFormattedNodeLibraryWarning {
            get {
                return ResourceManager.GetString("IncorrectlyFormattedNodeLibraryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file &apos;{0}&apos; was created in future version &apos;{1}&apos; and may not open correctly in your installed version of Dynamo &apos;{2}&apos;.
        /// </summary>
        public static string IncorrectVersionToOpenFile {
            get {
                return ResourceManager.GetString("IncorrectVersionToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT.
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function parameter, use with custom nodes.
        /// </summary>
        public static string InputNodeDescription {
            get {
                return ResourceManager.GetString("InputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable;argument;parameter.
        /// </summary>
        public static string InputNodeSearchTags {
            get {
                return ResourceManager.GetString("InputNodeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        public static string InputPortAlternativeName {
            get {
                return ResourceManager.GetString("InputPortAlternativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Dynamo Definition....
        /// </summary>
        public static string InsertDialogBoxText {
            get {
                return ResourceManager.GetString("InsertDialogBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example file added to workspace. Run mode changed to Manual..
        /// </summary>
        public static string InsertGraphRunModeNotificationText {
            get {
                return ResourceManager.GetString("InsertGraphRunModeNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; does not exist.
        /// </summary>
        public static string InvalidCustomNodeFolderWarning {
            get {
                return ResourceManager.GetString("InvalidCustomNodeFolderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom node contains an invalid input. Please fix the input before saving the custom node..
        /// </summary>
        public static string InvalidInputSymbolCustomNodeWarning {
            get {
                return ResourceManager.GetString("InvalidInputSymbolCustomNodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input symbol is not currently valid, and cannot be saved until it is fixed. Valid inputs take the form:
        ///
        ///name : type = defaultValue
        ///
        ///The input name should be a valid variable name, without spaces. An input type and default value are optional..
        /// </summary>
        public static string InvalidInputSymbolErrorMessage {
            get {
                return ResourceManager.GetString("InvalidInputSymbolErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom node currently contains some invalid inputs, and cannot be saved until the inputs are fixed. If the custom node is saved using SaveAs, the invalid inputs will revert to generic inputs. Valid inputs take the form:
        ///
        ///name : type = defaultValue
        ///
        ///The input name should be a valid variable name, without spaces. An input type and default value are optional..
        /// </summary>
        public static string InvalidInputSymbolWarningMessage {
            get {
                return ResourceManager.GetString("InvalidInputSymbolWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom node cannot be saved until invalid inputs are removed or fixed..
        /// </summary>
        public static string InvalidInputSymbolWarningShortMessage {
            get {
                return ResourceManager.GetString("InvalidInputSymbolWarningShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Node Contains Invalid Inputs and Cannot Be Saved..
        /// </summary>
        public static string InvalidInputSymbolWarningTitle {
            get {
                return ResourceManager.GetString("InvalidInputSymbolWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid library format..
        /// </summary>
        public static string InvalidLibraryFormat {
            get {
                return ResourceManager.GetString("InvalidLibraryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the package called {0} found at {1} is invalid (version: &quot;{2}&quot;). Ignoring it..
        /// </summary>
        public static string InvalidPackageVersion {
            get {
                return ResourceManager.GetString("InvalidPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start or end of a range is greater than the number of available elements in the list..
        /// </summary>
        public static string InvalidStartOrEndOfRange {
            get {
                return ResourceManager.GetString("InvalidStartOrEndOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build error for library: {0}.
        /// </summary>
        public static string LibraryBuildError {
            get {
                return ResourceManager.GetString("LibraryBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library {0} has been loaded..
        /// </summary>
        public static string LibraryHasBeenLoaded {
            get {
                return ResourceManager.GetString("LibraryHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is dumped to \&quot;{0}\&quot;..
        /// </summary>
        public static string LibraryIsDumped {
            get {
                return ResourceManager.GetString("LibraryIsDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This assembly is likely blocked. Try importing it again after unblocking the assembly..
        /// </summary>
        public static string LibraryLoadFailureForBlockedAssembly {
            get {
                return ResourceManager.GetString("LibraryLoadFailureForBlockedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library load failure.
        /// </summary>
        public static string LibraryLoadFailureMessageBoxTitle {
            get {
                return ResourceManager.GetString("LibraryLoadFailureMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find library path: {0}..
        /// </summary>
        public static string LibraryPathCannotBeFound {
            get {
                return ResourceManager.GetString("LibraryPathCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading node definition for &quot;{0}&quot; from: {1}.
        /// </summary>
        public static string LoadingNodeDefinition {
            get {
                return ResourceManager.GetString("LoadingNodeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate in Disk...
        /// </summary>
        public static string LocateInDisk {
            get {
                return ResourceManager.GetString("LocateInDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login to your account to get recommendations. Please log in or switch to node type match autocomplete..
        /// </summary>
        public static string LoginNeededMessage {
            get {
                return ResourceManager.GetString("LoginNeededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated.
        /// </summary>
        public static string LoginNeededTitle {
            get {
                return ResourceManager.GetString("LoginNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains a package with a malformed header.  Ignoring it..
        /// </summary>
        public static string MalformedHeaderPackage {
            get {
                return ResourceManager.GetString("MalformedHeaderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} cannot be loaded. 
        ///Installing it will conflict with one or more node definitions that already exist in {0}, which is currently loaded. 
        ///To install {1}, Dynamo needs to first uninstall {0}. 
        ///Restart Dynamo to complete the uninstall..
        /// </summary>
        public static string MessageCustomNodePackageFailedToLoad {
            get {
                return ResourceManager.GetString("MessageCustomNodePackageFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing some XML documentation tags..
        /// </summary>
        public static string MissingXmlTagConsoleMessage {
            get {
                return ResourceManager.GetString("MissingXmlTagConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateModelValue: Model not found.
        /// </summary>
        public static string ModelNotFoundError {
            get {
                return ResourceManager.GetString("ModelNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW MORE ({0}).
        /// </summary>
        public static string MoreButtonTextFormat {
            get {
                return ResourceManager.GetString("MoreButtonTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Note.
        /// </summary>
        public static string NewNoteString {
            get {
                return ResourceManager.GetString("NewNoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &apos;{0}&apos; is now deprecated..
        /// </summary>
        public static string NodeDeprecatedMsg {
            get {
                return ResourceManager.GetString("NodeDeprecatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all errors.
        /// </summary>
        public static string NodeInformationalStateShowAllErrors {
            get {
                return ResourceManager.GetString("NodeInformationalStateShowAllErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node &apos;{0}&apos; cannot be resolved..
        /// </summary>
        public static string NodeNotResolvedMsg {
            get {
                return ResourceManager.GetString("NodeNotResolvedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node of type &apos;{0}&apos;,from assembly &apos;{1}&apos;, is now deprecated..
        /// </summary>
        public static string NodeOfTypeDeprecatedMsg {
            get {
                return ResourceManager.GetString("NodeOfTypeDeprecatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node of type &apos;{0}&apos;, from assembly &apos;{1}&apos;, cannot be resolved..
        /// </summary>
        public static string NodeOfTypeNotResolvedMsg {
            get {
                return ResourceManager.GetString("NodeOfTypeNotResolvedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whilst preparing to run, this node encountered a problem. Please talk to the creators of the node, and give them this message:.
        /// </summary>
        public static string NodeProblemEncountered {
            get {
                return ResourceManager.GetString("NodeProblemEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available.
        /// </summary>
        public static string NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled &apos;DummyNode.NodeNature&apos; value: {0}.
        /// </summary>
        public static string NodeUnhandledMsg {
            get {
                return ResourceManager.GetString("NodeUnhandledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains a package without a header.  Ignoring it..
        /// </summary>
        public static string NoHeaderPackage {
            get {
                return ResourceManager.GetString("NoHeaderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneLinterDescriptorName {
            get {
                return ResourceManager.GetString("NoneLinterDescriptorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string NoneString {
            get {
                return ResourceManager.GetString("NoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is selected. href=NothingIsSelectedWarning.html.
        /// </summary>
        public static string NothingIsSelectedWarning {
            get {
                return ResourceManager.GetString("NothingIsSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a number..
        /// </summary>
        public static string NumberNodeDescription {
            get {
                return ResourceManager.GetString("NumberNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file &apos;{0}&apos; of version &apos;{1}&apos; cannot be opened by this version of Dynamo ({2}).
        /// </summary>
        public static string ObsoleteFileDescription {
            get {
                return ResourceManager.GetString("ObsoleteFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete File.
        /// </summary>
        public static string ObsoleteFileTitle {
            get {
                return ResourceManager.GetString("ObsoleteFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening home workspace {0}....
        /// </summary>
        public static string OpeningHomeWorkspace {
            get {
                return ResourceManager.GetString("OpeningHomeWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the workbench..
        /// </summary>
        public static string OpenWorkbenchError {
            get {
                return ResourceManager.GetString("OpenWorkbenchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the workspace..
        /// </summary>
        public static string OpenWorkspaceError {
            get {
                return ResourceManager.GetString("OpenWorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUT.
        /// </summary>
        public static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function output, use with custom nodes.
        /// </summary>
        public static string OutputNodeDescription {
            get {
                return ResourceManager.GetString("OutputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output.
        /// </summary>
        public static string OutputPortAlternativeName {
            get {
                return ResourceManager.GetString("OutputPortAlternativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package was found to be empty and was not installed..
        /// </summary>
        public static string PackageEmpty {
            get {
                return ResourceManager.GetString("PackageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This package likely contains an assembly that is blocked. You will need to load the package again after unblocking the assembly. Restart Dynamo to reload the package..
        /// </summary>
        public static string PackageLoadFailureForBlockedAssembly {
            get {
                return ResourceManager.GetString("PackageLoadFailureForBlockedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A package with the given name already exists..
        /// </summary>
        public static string PackageManagerPackageAlreadyExists {
            get {
                return ResourceManager.GetString("PackageManagerPackageAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user, &apos;{0}&apos;, is not a maintainer of the package &apos;{1}&apos;..
        /// </summary>
        public static string PackageManagerUserIsNotAMaintainer {
            get {
                return ResourceManager.GetString("PackageManagerUserIsNotAMaintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PackageStateError {
            get {
                return ResourceManager.GetString("PackageStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded.
        ///This package has not been loaded due to an unexpected error..
        /// </summary>
        public static string PackageStateErrorTooltip {
            get {
                return ResourceManager.GetString("PackageStateErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string PackageStateLoaded {
            get {
                return ResourceManager.GetString("PackageStateLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        ///This package is loaded and ready to be used..
        /// </summary>
        public static string PackageStateLoadedTooltip {
            get {
                return ResourceManager.GetString("PackageStateLoadedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled to be unloaded.
        /// </summary>
        public static string PackageStatePendingUnload {
            get {
                return ResourceManager.GetString("PackageStatePendingUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled to be unloaded.
        ///This package will be unloaded after the next Dynamo restart..
        /// </summary>
        public static string PackageStatePendingUnloadTooltip {
            get {
                return ResourceManager.GetString("PackageStatePendingUnloadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded.
        /// </summary>
        public static string PackageStateUnloaded {
            get {
                return ResourceManager.GetString("PackageStateUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded.
        ///This package has not been loaded because another conflicting package was loaded before it..
        /// </summary>
        public static string PackageStateUnloadedTooltip {
            get {
                return ResourceManager.GetString("PackageStateUnloadedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package is too large!  The package must be less than 15 MB!.
        /// </summary>
        public static string PackageTooLarge {
            get {
                return ResourceManager.GetString("PackageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file path is not recognizable as a stable or a daily build.
        /// </summary>
        public static string PathNotRegconizableAsStableOrDailyBuild {
            get {
                return ResourceManager.GetString("PathNotRegconizableAsStableOrDailyBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function output.
        /// </summary>
        public static string PortDataFunctionOutputToolTip {
            get {
                return ResourceManager.GetString("PortDataFunctionOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input #{0}.
        /// </summary>
        public static string PortDataInputToolTip {
            get {
                return ResourceManager.GetString("PortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output #{0}.
        /// </summary>
        public static string PortDataOutputToolTip {
            get {
                return ResourceManager.GetString("PortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        public static string PortDataParameterToolTip {
            get {
                return ResourceManager.GetString("PortDataParameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the file.
        /// </summary>
        public static string PortDataPathToFileToolTip {
            get {
                return ResourceManager.GetString("PortDataPathToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return value.
        /// </summary>
        public static string PortDataReturnValueToolTip {
            get {
                return ResourceManager.GetString("PortDataReturnValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string PortDataSymbolToolTip {
            get {
                return ResourceManager.GetString("PortDataSymbolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        public static string PortDataVariableToolTip {
            get {
                return ResourceManager.GetString("PortDataVariableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of port names does not equal number of port descriptions..
        /// </summary>
        public static string PortsNameDescriptionDoNotEqualWarningMessage {
            get {
                return ResourceManager.GetString("PortsNameDescriptionDoNotEqualWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D preview has been deactivated.
        /// </summary>
        public static string Preview3DOutageTitle {
            get {
                return ResourceManager.GetString("Preview3DOutageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed anyway.
        /// </summary>
        public static string ProceedButton {
            get {
                return ResourceManager.GetString("ProceedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python template loaded from AppData.
        /// </summary>
        public static string PythonTemplateAppData {
            get {
                return ResourceManager.GetString("PythonTemplateAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python template set to default..
        /// </summary>
        public static string PythonTemplateDefaultFile {
            get {
                return ResourceManager.GetString("PythonTemplateDefaultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python template set by host integrator.
        /// </summary>
        public static string PythonTemplateDefinedByHost {
            get {
                return ResourceManager.GetString("PythonTemplateDefinedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python template loaded from DynamoSettings.xml path.
        /// </summary>
        public static string PythonTemplateUserFile {
            get {
                return ResourceManager.GetString("PythonTemplateUserFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range end could not be parsed..
        /// </summary>
        public static string RangeEndCouldNotBeParsed {
            get {
                return ResourceManager.GetString("RangeEndCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use range or approx. identifier on increment field when one has already been used to specify a count..
        /// </summary>
        public static string RangeOrApprIdentifierAlrUsed {
            get {
                return ResourceManager.GetString("RangeOrApprIdentifierAlrUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of numbers or letters in the sequence
        ///Default value: 10.
        /// </summary>
        public static string RangePortDataAmountToolTip {
            get {
                return ResourceManager.GetString("RangePortDataAmountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number or letter to end the sequence at
        ///Default value: 9.
        /// </summary>
        public static string RangePortDataEndToolTip {
            get {
                return ResourceManager.GetString("RangePortDataEndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New list of type: var[]..[].
        /// </summary>
        public static string RangePortDataSeqToolTip {
            get {
                return ResourceManager.GetString("RangePortDataSeqToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number or letter to start the sequence at
        ///Default value: 0.
        /// </summary>
        public static string RangePortDataStartToolTip {
            get {
                return ResourceManager.GetString("RangePortDataStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between numbers or letters
        ///Default value: 1.
        /// </summary>
        public static string RangePortDataStepToolTip {
            get {
                return ResourceManager.GetString("RangePortDataStepToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range step could not be parsed..
        /// </summary>
        public static string RangeStepCouldNotBeParsed {
            get {
                return ResourceManager.GetString("RangeStepCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range values must be greater than zero..
        /// </summary>
        public static string RangeValuesGreaterThanZero {
            get {
                return ResourceManager.GetString("RangeValuesGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveLabel {
            get {
                return ResourceManager.GetString("RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting version update info....
        /// </summary>
        public static string RequestingVersionUpdate {
            get {
                return ResourceManager.GetString("RequestingVersionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Property is not String Type.
        /// </summary>
        public static string ResourcePropertyIsNotStringTypeMessage {
            get {
                return ResourceManager.GetString("ResourcePropertyIsNotStringTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type does not have Property.
        /// </summary>
        public static string ResourceTypeDoesNotHavePropertyMessage {
            get {
                return ResourceManager.GetString("ResourceTypeDoesNotHavePropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run whenever an input to the graph is updated..
        /// </summary>
        public static string RunTypeToolTipAutomatically {
            get {
                return ResourceManager.GetString("RunTypeToolTipAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run when you click the Run button..
        /// </summary>
        public static string RunTypeToolTipManually {
            get {
                return ResourceManager.GetString("RunTypeToolTipManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Periodic is only available when there are nodes in the graph that support periodic update..
        /// </summary>
        public static string RunTypeToolTipPeriodicallyDisabled {
            get {
                return ResourceManager.GetString("RunTypeToolTipPeriodicallyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at the specified interval..
        /// </summary>
        public static string RunTypeToolTipPeriodicallyEnabled {
            get {
                return ResourceManager.GetString("RunTypeToolTipPeriodicallyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0} ....
        /// </summary>
        public static string SavingInProgress {
            get {
                return ResourceManager.GetString("SavingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTextBlockText {
            get {
                return ResourceManager.GetString("SearchTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing preferences....
        /// </summary>
        public static string SplashScreenInitPreferencesSettings {
            get {
                return ResourceManager.GetString("SplashScreenInitPreferencesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Node Library....
        /// </summary>
        public static string SplashScreenLoadNodeLibrary {
            get {
                return ResourceManager.GetString("SplashScreenLoadNodeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a string..
        /// </summary>
        public static string StringNodeDescription {
            get {
                return ResourceManager.GetString("StringNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sublists..
        /// </summary>
        public static string SublistPortDataResultToolTip {
            get {
                return ResourceManager.GetString("SublistPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list from which to create sublists..
        /// </summary>
        public static string SublistsPortDataListToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset to apply to the sub-list. Ex. The range &quot;0..2&quot; with an offset of 1 will yield sublists {0,1,2}{1,2,3}{2,3,4}....
        /// </summary>
        public static string SublistsPortDataOffsetToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataOffsetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Bug To Github.
        /// </summary>
        public static string SubmitBugButton {
            get {
                return ResourceManager.GetString("SubmitBugButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Bug To Github.
        /// </summary>
        public static string SubmitBugToGithub {
            get {
                return ResourceManager.GetString("SubmitBugToGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function parameter, use with custom nodes.
        ///
        ///You can specify the type and default value for parameter. E.g.,
        ///
        ///input : var[]..[]
        ///value : bool = false.
        /// </summary>
        public static string SymbolNodeDescription {
            get {
                return ResourceManager.GetString("SymbolNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable;argument;parameter.
        /// </summary>
        public static string SymbolSearchTags {
            get {
                return ResourceManager.GetString("SymbolSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Output.
        /// </summary>
        public static string ToolTipForTempVar {
            get {
                return ResourceManager.GetString("ToolTipForTempVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function output.
        /// </summary>
        public static string ToolTipFunctionOutput {
            get {
                return ResourceManager.GetString("ToolTipFunctionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input #.
        /// </summary>
        public static string ToolTipInput {
            get {
                return ResourceManager.GetString("ToolTipInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Data.
        /// </summary>
        public static string ToolTipInputData {
            get {
                return ResourceManager.GetString("ToolTipInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output #.
        /// </summary>
        public static string ToolTipOutput {
            get {
                return ResourceManager.GetString("ToolTipOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Data.
        /// </summary>
        public static string ToolTipOutputData {
            get {
                return ResourceManager.GetString("ToolTipOutputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return value.
        /// </summary>
        public static string ToolTipReturnValue {
            get {
                return ResourceManager.GetString("ToolTipReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Result.
        /// </summary>
        public static string TopResult {
            get {
                return ResourceManager.GetString("TopResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of custom node with id: \&quot;.
        /// </summary>
        public static string UnableToCreateCustomNodeID {
            get {
                return ResourceManager.GetString("UnableToCreateCustomNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in Dynamo engine.
        /// </summary>
        public static string UnhandledExceptionInDynamoEngine {
            get {
                return ResourceManager.GetString("UnhandledExceptionInDynamoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception in Dynamo engine.
        /// </summary>
        public static string UnhandledExceptionSummary {
            get {
                return ResourceManager.GetString("UnhandledExceptionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may be caused by a missing package, incompatible package version, or missing host program. If you Save As, the unresolved nodes will be removed.
        ///
        ///Resolve or remove the unresolved nodes and try again..
        /// </summary>
        public static string UnresolvedNodesWarningMessage {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph has unresolved nodes and cannot be saved..
        /// </summary>
        public static string UnresolvedNodesWarningShortMessage {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save graph.
        /// </summary>
        public static string UnresolvedNodesWarningTitle {
            get {
                return ResourceManager.GetString("UnresolvedNodesWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: {0}.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download complete..
        /// </summary>
        public static string UpdateDownloadComplete {
            get {
                return ResourceManager.GetString("UpdateDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download progress: {0}%.
        /// </summary>
        public static string UpdateDownloadProgress {
            get {
                return ResourceManager.GetString("UpdateDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download started....
        /// </summary>
        public static string UpdateDownloadStarted {
            get {
                return ResourceManager.GetString("UpdateDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh...
        /// We&apos;re sorry - we tried to save your decisions, but something went wrong. The decision probably hasn&apos;t been saved. This really shouldn&apos;t have happened. Please get in touch via GitHub and send us this information.
        ///You can also try deleting [FILEPATH] and trying again.
        ///Depending on your previous choice, analytics may still be running, if you&apos;re worried about this, please consider not using Dynamo until we&apos;ve got back to you to solve the problem.
        ///Sorry about that..
        /// </summary>
        public static string UsageReportingErrorMessage {
            get {
                return ResourceManager.GetString("UsageReportingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type &apos;{0}&apos;.
        /// </summary>
        public static string WarningCannotFindType {
            get {
                return ResourceManager.GetString("WarningCannotFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        ///
        ///The name of parameter should start with alphabetic character. You can specify its type and default value. E.g., 
        ///
        ///input : var[]..[]
        ///value: bool = false.
        /// </summary>
        public static string WarningInvalidInput {
            get {
                return ResourceManager.GetString("WarningInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only comments and single variable are allowed in output node..
        /// </summary>
        public static string WarningInvalidOutput {
            get {
                return ResourceManager.GetString("WarningInvalidOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code here.
        /// </summary>
        public static string WatermarkLabelText {
            get {
                return ResourceManager.GetString("WatermarkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dynamo!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbench could not be opened..
        /// </summary>
        public static string WorkbenchNotOpen {
            get {
                return ResourceManager.GetString("WorkbenchNotOpen", resourceCulture);
            }
        }
    }
}
