//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dynamo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dynamo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build sublists from a list using DesignScript range syntax..
        /// </summary>
        public static string BuildSublistsDescription {
            get {
                return ResourceManager.GetString("BuildSublistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for DesignScript code to be authored directly.
        /// </summary>
        public static string CodeBlockNodeDescription {
            get {
                return ResourceManager.GetString("CodeBlockNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composes two single parameter functions into one function..
        /// </summary>
        public static string ComposeFunctionNodeDescription {
            get {
                return ResourceManager.GetString("ComposeFunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Function.
        /// </summary>
        public static string ComposeFunctionPortDataFunctionToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataFunctionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composed function: g(f(x)).
        /// </summary>
        public static string ComposeFunctionPortDataResultToolTip {
            get {
                return ResourceManager.GetString("ComposeFunctionPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of a Custom Node.
        /// </summary>
        public static string CustomNodeDesciption {
            get {
                return ResourceManager.GetString("CustomNodeDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignScript Builtin Functions.
        /// </summary>
        public static string FunctionNodeDescription {
            get {
                return ResourceManager.GetString("FunctionNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function parameter, use with custom nodes.
        /// </summary>
        public static string InputNodeDescription {
            get {
                return ResourceManager.GetString("InputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable;argument;parameter.
        /// </summary>
        public static string InputNodeSearchTags {
            get {
                return ResourceManager.GetString("InputNodeSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a number..
        /// </summary>
        public static string NumberNodeDescription {
            get {
                return ResourceManager.GetString("NumberNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of numbers in the sequence.
        /// </summary>
        public static string NumberRangePortDataAmountToolTip {
            get {
                return ResourceManager.GetString("NumberRangePortDataAmountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to end the sequence at.
        /// </summary>
        public static string NumberRangePortDataEndToolTip {
            get {
                return ResourceManager.GetString("NumberRangePortDataEndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sequence.
        /// </summary>
        public static string NumberRangePortDataSeqToolTip {
            get {
                return ResourceManager.GetString("NumberRangePortDataSeqToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to start the sequence at.
        /// </summary>
        public static string NumberRangePortDataStartToolTip {
            get {
                return ResourceManager.GetString("NumberRangePortDataStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between numbers.
        /// </summary>
        public static string NumberRangePortDataStepToolTip {
            get {
                return ResourceManager.GetString("NumberRangePortDataStepToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A function output, use with custom nodes.
        /// </summary>
        public static string OutputNodeDescription {
            get {
                return ResourceManager.GetString("OutputNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        public static string PortDataParameterToolTip {
            get {
                return ResourceManager.GetString("PortDataParameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        public static string PortDataVariableToolTip {
            get {
                return ResourceManager.GetString("PortDataVariableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a string..
        /// </summary>
        public static string StringNodeDescription {
            get {
                return ResourceManager.GetString("StringNodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sublists..
        /// </summary>
        public static string SublistPortDataResultToolTip {
            get {
                return ResourceManager.GetString("SublistPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list from which to create sublists..
        /// </summary>
        public static string SublistsPortDataListToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset to apply to the sub-list. Ex. The range &quot;0..2&quot; with an offset of 1 will yield sublists {0,1,2}{1,2,3}{2,3,4}....
        /// </summary>
        public static string SublistsPortDataOffsetToolTip {
            get {
                return ResourceManager.GetString("SublistsPortDataOffsetToolTip", resourceCulture);
            }
        }
    }
}
