<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>EmbeddedInterop</RootNamespace>
    <AssemblyName>EmbeddedInterop</AssemblyName>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Office.Interop.Excel" GeneratePathProperty="true">
            <ExcludeAssets>all</ExcludeAssets>
        </PackageReference>
        <Reference Include="$(PkgMicrosoft_Office_Interop_Excel)\lib\net20\Microsoft.Office.Interop.Excel.dll">
            <EmbedInteropTypes>True</EmbedInteropTypes>
            <WrapperTool>tlbimp</WrapperTool>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
  <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
