//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoImperative {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoImperative.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array declaration expected constant expression.
        /// </summary>
        internal static string logSemanticErrorArrayDeclarationExpectedConstantExpression {
            get {
                return ResourceManager.GetString("logSemanticErrorArrayDeclarationExpectedConstantExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array initializer must be an expression list.
        /// </summary>
        internal static string logSemanticErrorArrayInitializer {
            get {
                return ResourceManager.GetString("logSemanticErrorArrayInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array size overflow.
        /// </summary>
        internal static string logSemanticErrorArraySizeOverFlow {
            get {
                return ResourceManager.GetString("logSemanticErrorArraySizeOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a class name, can&apos;t be used as a variable..
        /// </summary>
        internal static string logSemanticErrorClassName {
            get {
                return ResourceManager.GetString("logSemanticErrorClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a function and not allowed as a variable name.
        /// </summary>
        internal static string logSemanticErrorFunction {
            get {
                return ResourceManager.GetString("logSemanticErrorFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function pointer is not allowed at binary expression other than assignment!.
        /// </summary>
        internal static string logSemanticErrorFunctionPointerIsNotAllowedAtBinaryExpression {
            get {
                return ResourceManager.GetString("logSemanticErrorFunctionPointerIsNotAllowedAtBinaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redefinition of identifier &apos;.
        /// </summary>
        internal static string logSemanticErrorRedefinitionOfIdentifier {
            get {
                return ResourceManager.GetString("logSemanticErrorRedefinitionOfIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An imperative language block is declared within an imperative language block..
        /// </summary>
        internal static string logSyntaxErrorImperativeLanguageBlockIsDeclareInside {
            get {
                return ResourceManager.GetString("logSyntaxErrorImperativeLanguageBlockIsDeclareInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only identifier or identifier list can appear on the left hand side of assignment..
        /// </summary>
        internal static string logSyntaxErrorOnlyIdentifierOrIdentifierListCanAppearOnLeftSide {
            get {
                return ResourceManager.GetString("logSyntaxErrorOnlyIdentifierOrIdentifierListCanAppearOnLeftSide", resourceCulture);
            }
        }
    }
}
