//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallUpdate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstallUpdate.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamo Update.
        /// </summary>
        internal static string CheckHostProcessWindowTitle {
            get {
                return ResourceManager.GetString("CheckHostProcessWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  must be closed before continuing installation. When the application is closed, select OK to continue updating, or Cancel to quit updating..
        /// </summary>
        internal static string CloseContinuationMessage {
            get {
                return ResourceManager.GetString("CloseContinuationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host application process id could not be parsed from the specified input..
        /// </summary>
        internal static string HostApplicationIdParseErrorMessage {
            get {
                return ResourceManager.GetString("HostApplicationIdParseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reinstall Dynamo manually..
        /// </summary>
        internal static string ManualReinstallMessage {
            get {
                return ResourceManager.GetString("ManualReinstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dynamo certificate could not be found. Update cancelled..
        /// </summary>
        internal static string MissingDynamoCertificateMessage {
            get {
                return ResourceManager.GetString("MissingDynamoCertificateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A signature file could not be found to verify this update..
        /// </summary>
        internal static string MissingSignatureFileMessage {
            get {
                return ResourceManager.GetString("MissingSignatureFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to quit..
        /// </summary>
        internal static string ProcessQuitMessage {
            get {
                return ResourceManager.GetString("ProcessQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the security certificate. Update cancelled..
        /// </summary>
        internal static string SecurityCertificateErrorMessage {
            get {
                return ResourceManager.GetString("SecurityCertificateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update could not be verified against the signature file..
        /// </summary>
        internal static string SignatureVerificationFailureMessage {
            get {
                return ResourceManager.GetString("SignatureVerificationFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update was cancelled..
        /// </summary>
        internal static string UpdateCancellationMessage {
            get {
                return ResourceManager.GetString("UpdateCancellationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify the update download.
        /// </summary>
        internal static string UpdateDownloadVerificationFailedMessage {
            get {
                return ResourceManager.GetString("UpdateDownloadVerificationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file path does not exist..
        /// </summary>
        internal static string UpdaterPathNotFoundMessage {
            get {
                return ResourceManager.GetString("UpdaterPathNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the path of the update..
        /// </summary>
        internal static string UpdaterPathRequiredMessage {
            get {
                return ResourceManager.GetString("UpdaterPathRequiredMessage", resourceCulture);
            }
        }
    }
}
