//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamoUnits.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamoUnits.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_ByTypeIDDescription {
            get {
                return ResourceManager.GetString("Quantity.ByTypeIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_ByTypeIDSearchTags {
            get {
                return ResourceManager.GetString("Quantity.ByTypeIDSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_ByTypeIDToolTip {
            get {
                return ResourceManager.GetString("Quantity.ByTypeIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_NameDescription {
            get {
                return ResourceManager.GetString("Quantity.NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_NameSearchTags {
            get {
                return ResourceManager.GetString("Quantity.NameSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_NameToolTip {
            get {
                return ResourceManager.GetString("Quantity.NameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_TypeIdDescription {
            get {
                return ResourceManager.GetString("Quantity.TypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_TypeIdSearchTags {
            get {
                return ResourceManager.GetString("Quantity.TypeIdSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_TypeIdToolTip {
            get {
                return ResourceManager.GetString("Quantity.TypeIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_UnitsDescription {
            get {
                return ResourceManager.GetString("Quantity.UnitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_UnitsSearchTags {
            get {
                return ResourceManager.GetString("Quantity.UnitsSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Quantity_UnitsToolTip {
            get {
                return ResourceManager.GetString("Quantity.UnitsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_AreUnitsConvertibleDescription {
            get {
                return ResourceManager.GetString("Unit.AreUnitsConvertibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_AreUnitsConvertibleSearchTags {
            get {
                return ResourceManager.GetString("Unit.AreUnitsConvertibleSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_AreUnitsConvertibleToolTip {
            get {
                return ResourceManager.GetString("Unit.AreUnitsConvertibleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ByTypeIDDescription {
            get {
                return ResourceManager.GetString("Unit.ByTypeIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ByTypeIDSearchTags {
            get {
                return ResourceManager.GetString("Unit.ByTypeIDSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ByTypeIDToolTip {
            get {
                return ResourceManager.GetString("Unit.ByTypeIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ConvertibleUnitsDescription {
            get {
                return ResourceManager.GetString("Unit.ConvertibleUnitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ConvertibleUnitsSearchTags {
            get {
                return ResourceManager.GetString("Unit.ConvertibleUnitsSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_ConvertibleUnitsToolTip {
            get {
                return ResourceManager.GetString("Unit.ConvertibleUnitsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_NameDescription {
            get {
                return ResourceManager.GetString("Unit.NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_NameSearchTags {
            get {
                return ResourceManager.GetString("Unit.NameSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_NameToolTip {
            get {
                return ResourceManager.GetString("Unit.NameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_QuantitiesContainingUnitDescription {
            get {
                return ResourceManager.GetString("Unit.QuantitiesContainingUnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_QuantitiesContainingUnitSearchTags {
            get {
                return ResourceManager.GetString("Unit.QuantitiesContainingUnitSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_QuantitiesContainingUnitToolTip {
            get {
                return ResourceManager.GetString("Unit.QuantitiesContainingUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_TypeIdDescription {
            get {
                return ResourceManager.GetString("Unit.TypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_TypeIdSearchTags {
            get {
                return ResourceManager.GetString("Unit.TypeIdSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Unit_TypeIdToolTip {
            get {
                return ResourceManager.GetString("Unit.TypeIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_ByTypeIDDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.ByTypeIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_ByTypeIDSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.ByTypeIDSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_ByTypeIDToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.ByTypeIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SpaceDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.SpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SpaceSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.SpaceSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SpaceToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.SpaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyDecimalDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyDecimalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyDecimalSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyDecimalSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyDecimalToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyDecimalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyFractionDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyFractionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyFractionSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyFractionSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_StringifyFractionToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.StringifyFractionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SymbolsByUnitDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.SymbolsByUnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SymbolsByUnitSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.SymbolsByUnitSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_SymbolsByUnitToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.SymbolsByUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TextDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TextSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.TextSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TextToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.TextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TypeIdDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.TypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TypeIdSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.TypeIdSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_TypeIdToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.TypeIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_UnitDescription {
            get {
                return ResourceManager.GetString("UnitSymbol.UnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_UnitSearchTags {
            get {
                return ResourceManager.GetString("UnitSymbol.UnitSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string UnitSymbol_UnitToolTip {
            get {
                return ResourceManager.GetString("UnitSymbol.UnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitIdsDescription {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitIdsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitIdsSearchTags {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitIdsSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitIdsToolTip {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitIdsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitsDescription {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitsSearchTags {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitsSearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string Utilities_ConvertByUnitsToolTip {
            get {
                return ResourceManager.GetString("Utilities.ConvertByUnitsToolTip", resourceCulture);
            }
        }
    }
}
