# Build DynamoCore.sln with .NET 6.0 on windows
name: Build DynamoCore.sln net6.0 windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v4
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Disable problem matcher
      run: echo "::remove-matcher owner=csc::"

    - name: Install dependencies for windows runtime
      run: |
        dotnet restore $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.sln /p:Configuration=Release --runtime=win-x64
    - name: Build Dynamo with MSBuild for Windows
      run: |
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.sln  /p:Configuration=Release
    # look for Dynamo
    - name: Navigate to Dynamo Windows Folder
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\AnyCPU\Release"
        echo "***Locating DynamoCLI for Windows!***"
        test ".\DynamoCLI.exe" && echo "DynamoCLI exists!"
    - name: Install dependencies for linux runtime
      run: dotnet restore $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.sln -p:Platform=NET60_Linux --runtime=linux-x64
    - name: Build Dynamo with MSBuild for Linux
      run: |
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.sln /p:Configuration=Release /p:Platform=NET60_Linux
    - name: Navigate to Dynamo Linux Folder
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\NET60_Linux\Release"
        echo "***Locating DynamoCLI for Linux!***"
        test ".\DynamoCLI.exe" && echo "DynamoCLI exists!"
