# Build DynamoCore.sln with .NET 6.0 on windows
name: Build DynamoCore.sln net6.0 windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Dynamo Repo
        uses: actions/checkout@v4
        with:
          path: Dynamo
          repository: DynamoDS/Dynamo
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Disable problem matcher
        run: Write-Output "::remove-matcher owner=csc::"
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3
      - name: Install dependencies for windows runtime
        run: |
          dotnet restore ${{ github.workspace }}\Dynamo\src\DynamoCore.sln /p:Configuration=Release --runtime=win-x64
      - name: Build Dynamo with MSBuild for Windows
        run: |
          Write-Output "***Continue with the build, Good luck developer!***"
          msbuild ${{ github.workspace }}\Dynamo\src\DynamoCore.sln /p:Configuration=Release
      - name: Look for DynamoCLI.exe
        run: |
          Write-Output "***Locating DynamoCLI.exe!***"
          if (Test-Path -Path "${{ github.workspace }}\Dynamo\bin\AnyCPU\Release\DynamoCLI.exe") {
            Write-Output "DynamoCLI.exe exists!"
          } else {
            Write-Error "DynamoCLI.exe was not found!"
          }
      - name: Install dependencies for linux runtime
        run: dotnet restore ${{ github.workspace }}\Dynamo\src\DynamoCore.sln -p:Platform=NET_Linux --runtime=linux-x64
      - name: Build Dynamo with MSBuild for Linux
        run: |
          Write-Output "***Continue with the build, Good luck developer!***"
          msbuild ${{ github.workspace }}\Dynamo\src\DynamoCore.sln /p:Configuration=Release /p:Platform=NET_Linux
      - name: Look for DynamoCLI
        run: |
          Write-Output "***Locating DynamoCLI for Linux!***"
          if (Test-Path -Path "${{ github.workspace }}\Dynamo\bin\NET_Linux\Release\DynamoCLI") {
            Write-Output "DynamoCLI exists!"
          } else {
            Write-Error "DynamoCLI was not found!"
          }
