# Runs on completion of "Build DynamoAll.sln net8.0" workflow
#
# - Checks file version of exes and dlls
# - Fails if any file is missing version information
# - Fails if any Dynamo related files have incorrect version information
name: Check file version

on:
  workflow_run:
    workflows:
      - Build DynamoAll.sln net8.0
    types:
      - completed

jobs:
  check_file_version:
    name: Check file version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Download build artifact
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          github-token: ${{ secrets.DYNAMO_ACTIONS_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: build
          path: build
      - name: Check file version
        run: ${{ github.workspace }}\.github\scripts\check_file_version.ps1 ${{ github.workspace }}\build
