# Build Dynamo using latest VS and DotNET
name: Dynamo-net6.0-Build
on: [push,pull_request]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v2
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
   
    - name: Install dependencies for linux runtime
      run: dotnet restore $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.net6.sln -p:Platform=NET60_Linux --runtime=linux-x64
    - name: Build Dynamo with MSBuild for Linux
      run: |
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\DynamoCore.net6.sln /p:Configuration=Release /p:Platform=NET60_Linux
    - name: Navigate to Dynamo Linux Folder
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\NET60_Linux\Release"
        echo "***Locating DynamoCLI for Linux!***"
        test ".\DynamoCLI.exe" && echo "DynamoCLI exists!"
    - name: Run smoke tests
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\NET60_Linux\Release"
        echo "***Running Smoke tests on linux***"
        dotnet test --no-build bin\AnyCPU\Release\DynamoCoreTests.dll --test-adapter-path  ~\.nuget\packages\nunittestadapter\2.3.0\build\ --filter TestCategory=SmokeTest

       
