# Build Dynamo using latest VS and DotNET
name: Dynamo-VS2019Build
on: [push,pull_request]
jobs:
 build:
  runs-on: windows-latest
  steps:
    - name: Checkout Dynamo Repo
      uses: actions/checkout@v2
      with:
        path: Dynamo
        repository: DynamoDS/Dynamo
    - name: Setup Nuget.exe to use on VM
      uses: nuget/setup-nuget@v1
    - name: Nuget Restore in Dynamo solution
      run: nuget restore $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    - name: Build Dynamo with MSBuild
      run: |
        echo "***Continue with the build, Good luck developer!***"
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Dynamo\src\Dynamo.All.sln
    # look for Dynamo
    - name: Navigate to Dynamo Folder
      run: |
        cd "$Env:GITHUB_WORKSPACE\Dynamo\bin\AnyCPU\Debug"
        echo "***Locating DynamoSandbox!***"
        test ".\DynamoSandbox.exe" && echo "DynamoSandbox exists!"
