name: Move issue by labels
# This workflow transfers or moves issues based upon assigned labels.

# DynamoIssues project https://github.com/orgs/DynamoDS/projects/4
# Built-in workflow https://github.com/orgs/DynamoDS/projects/4/workflows

# The built-in workflow
#   - adds any new issues to DynamoIssues project
#   - sets status as 'Triage' when an item is added to the project
#   - sets status as 'Backlog' when an item is reopened
#   - sets status as 'Done' when an item is closed

# This workflow complements the built in workflow and
#   - moves issues labeled as 'Revit' to 'DynamoDS/DynamoRevit' repository
#   - moves issues labeled as 'Advance-Steel' to 'DynamoDS/Dynamo-Advance-Steel' repository
#   - moves issues labeled as 'Wishlist' to 'DynamoDS/DynamoWishlist' repository
#   - moves issues labeled as 'tracked' to 'Todo' column the project

on:
  issues:
    types: [labeled]

env:
  gh_organization: DynamoDS
  gh_token: ${{ secrets.DYNAMO_ISSUES_TOKEN }}
  project_id: 4
  bot_comment: 'FYI: @DynamoDS/dynamo'

jobs:
  issue_labeled:
    name: issue labeled
    strategy:
      matrix:
        include:
          - label: 'Revit'
            repoName: 'DynamoRevit'
          - label: 'Advance-Steel'
            repoName: 'Dynamo-Advance-Steel'
          - label: 'Wishlist'
            repoName: 'DynamoWishlist'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add comment
        if: github.event.label.name == matrix.label
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.bot_comment }}
          token: ${{ env.gh_token }}
      - name: (Label ${{ matrix.label }}) Move to ${{ matrix.repoName }}
        if: github.event.label.name == matrix.label
        run: gh issue transfer ${{ github.event.issue.number }} ${{ matrix.repoName }}
        env:
          GITHUB_TOKEN: ${{ env.gh_token }}
      - name: Move tracked issue to Todo
        if: github.event.label.name == tracked
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ env.gh_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo
