name: Move issue by labels
# This workflow transfers or moves issues based upon assigned labels.

# DynamoIssues project https://github.com/orgs/DynamoDS/projects/4
# Built-in workflow https://github.com/orgs/DynamoDS/projects/4/workflows

# The built-in workflow
#   - adds any new issues to DynamoIssues project
#   - sets status as 'Triage' when an item is added to the project
#   - sets status as 'Backlog' when an item is reopened
#   - sets status as 'Done' when an item is closed

# This workflow complements the built in workflow and
#   - moves issues labeled as 'Revit' to 'DynamoDS/DynamoRevit' repository
#   - moves issues labeled as 'Advance-Steel' to 'DynamoDS/Dynamo-Advance-Steel' repository
#   - moves issues labeled as 'Wishlist' to 'DynamoDS/DynamoWishlist' repository
#   - moves issues labeled as 'tracked' to 'Todo' column in the project

on:
  issues:
    types: [labeled]

env:
  gh_organization: DynamoDS
  gh_token: ${{ secrets.DYNAMO_ISSUES_TOKEN }}
  project_id: 4

jobs:
  issue_labeled_as_revit:
    name: Transfer issue labeled as 'Revit'
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Revit'
    steps:
      - uses: actions/checkout@v3
      - name: Transfer issue to DynamoRevit Repository
        run: gh issue transfer ${{ github.event.issue.number }} DynamoDS/DynamoRevit
        env:
          GITHUB_TOKEN: ${{ env.gh_token }}
  issue_labeled_as_dynamo_advance_steel:
    name: Transfer issue labeled as 'Advance-Steel'
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Advance-Steel'
    steps:
      - uses: actions/checkout@v3
      - name: Transfer issue to Dynamo-Advance-Steel Repository
        run: gh issue transfer ${{ github.event.issue.number }} DynamoDS/Dynamo-Advance-Steel
        env:
          GITHUB_TOKEN: ${{ env.gh_token }}
  issue_labeled_as_wishlist:
    name: Transfer issue labeled as 'Wishlist'
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Wishlist'
    steps:
      - uses: actions/checkout@v3
      - name: Transfer issue to DynamoWishlist Repository
        run: gh issue transfer ${{ github.event.issue.number }} DynamoDS/DynamoWishlist
        env:
          GITHUB_TOKEN: ${{ env.gh_token }}
  issue_labeled_as_tracked:
    name: Move issue labeled as 'tracked'
    runs-on: ubuntu-latest
    if: github.event.label.name == 'tracked'
    steps:
      - name: Move tracked issue to Todo
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ env.gh_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo
