name: Move issue by labels
on: 
  issues:
    types: [labeled]
jobs: 
  gitIssueTransfer:
    env:
      bot_comment: "FYI: @DynamoDS/dynamo"
    strategy:
      matrix: 
        include: 
          - label: 'Revit'
            repoName: 'DynamoRevit'
          - label: 'Advance-Steel'
            repoName: 'Dynamo-Advance-Steel'
          - label: 'Wishlist'
            repoName: 'DynamoWishlist'
    name: Move issues to corresponding repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #Adds a comment to the issue before moving it
      - name: Add comment
        if: (github.event.label.name == matrix.label)
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: ${{ env.bot_comment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #Move the issue depending on its labels
      - name: (Label ${{ matrix.label }}) Move to ${{ matrix.repoName }}
        if: (github.event.label.name == matrix.label)
        run: hub issue transfer ${{github.event.issue.number}} ${{matrix.repoName}}
        env:
          #Uses DYNAMOBOTTOKEN to allow interaction between repos
          GITHUB_TOKEN: ${{ secrets.DYNAMOBOTTOKEN }}